### ISSUE TITLE
Out of combat rezzing is possible in all boss encounters.

### ISSUE THREAD

**Issue by Lorilay2** [elysium-project/server#1003]
Bosses are only pulsing a zonewide combat aura once on the pull. This is allowing anyone who is taken out of combat during an encounter to use out-of-combat resurrection spells unless they enter the aggro range of the boss (after using a battle rez, soulstone, divine intervention, jumper cables, ankh, etc). This was not possible on retail (a zone-wide combat pulse was added to all bosses sometime after March 2006), as mentioned here:

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/144-temple-of-ahnqiraj-guide-aq40.html
> Out Of Combat ressing is not a possibility in this fight, because not only is the entire instance flagged in combat, but Skeram does a devastating AoE if anyone is outside a certain range of him (estimated about 100 yards.)

http://wowwiki.wikia.com/wiki/Anubisath_Defender
> Each mob has a zone-wide combat pulse when pulled. It's not possible to feign out of a pull or to reset a mob (without wiping). It's also not possible to change your gear based on what aspects the mob has. Plan ahead.

**Correct behavior:** bosses periodically pulse combat aura, as outlined here:

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/13015-how-do-aggro-threat-work-wow.html (1.12)
> - Bosses in-combat pulse. For most high level instance bosses, every tick (2 seconds) every player in the instance is added to the boss threat list when the boss is in combat.

**Comment by webdkpthroaway** [comment]
I'd also like to point out that this allows for all sorts of funky pulls on the 1 Anubisath Warder - 2 Obsidian Nullifiers packs, as there is a way to separate them and pull mobs individually, thus trivializing these trash packs.

**Comment by sknnbones** [comment]
>  It's not possible to feign out of a pull 

Does this refer to feign death specifically?

Wipe Recovery may be possible when combined with Goblin Jumper Cables, Goblin Jumper Cables XL, or Gnomish Army Knife.

Before patch 2.0.1, when traps could only be set out of combat, hunters often used this[Feign Death] ability to set traps during combat.

**It can be used to exit combat in order to drink water** or if one needs to go the bathroom in the middle of a fight (does not work during boss fights as of patch 2.3.0).

http://vanilla-wow.wikia.com/wiki/Feign_Death


Also, current retail wikia:

Using feign death exits the hunter from combat, allowing for such things as eating, mounting, or other activities not possible while in combat. This can also be helpful if needing to afk for a short duration, due to the fact that passing mobs will act as if the hunter is dead.

For hunters with large damage output, this can be used to wipe threat and avoid peeling targets off the tank. Due to its long duration, hunters should be mindful of not using it too early, just in case the ability is needed later. Wipe Recovery may also be possible when combined with [Goblin Jumper Cables], [Goblin Jumper Cables XL], or a [Gnomish Army Knife].

http://wowwiki.wikia.com/wiki/Feign_Death

**Comment by Lorilay2** [comment]
You can't feign out of a pull because the zonewide aggro puts your entire raid in combat. If you pull and FD, it will still aggro the raid.

**Comment by Lorilay2** [comment]
This issue is only marginally related to FD in that hunters can also remain out of combat indefinitely because the bosses are not pulsing their combat aura

**Comment by sknnbones** [comment]
Ahhh I understand now, so hunters can FD in raids, except in this raid encounter, it doesn't put you back in combat after you stop using FD (normally you cast Jumper cables from FD so it starts casting before you get retagged)

So a hunte can FD and then just start moving and they will still be out of combat?

**Comment by Zarant** [comment]
I've seen people logging out during the nefarian fight and then logging back in after the shadow flame and rezzing everyone. That was a long time ago on the old nost server though, not sure if the same bug persists. That might be somewhat related.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/55357-anathema-updates-27092017/
