### ISSUE TITLE
friendly town npcs show a red name enemy title on them 

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1009]
friendly town npcs show a red name enemy title on them 

wondering if this will ever be fixed

http://i.imgur.com/33CDK1s.png

**Comment by Phoosy** [comment]
If I remember correctly, it appears to be due to the guard having being attacked by an opposite faction member - it sets its hostility status to all players instead of the individual who engaged with them, thus causing the issue. Player pets also have a similar problem until you click on them, but clicking on the NPCs in this reported instance does not solve the problem. You can't actually *attack* them but it does not prevent you speaking with the NPC.

**Comment by sknnbones** [comment]
What about mind control spells/items (mind control/gnomish hat)

**Comment by Mostprovidedlinks** [comment]
@thepparker this been fixed?

**Comment by Mostprovidedlinks** [comment]
@thepparker this been fixed?

**Comment by Mostprovidedlinks** [comment]
I assume its fixed
