### ISSUE TITLE
Execute not triggering Chance on Hit

### ISSUE THREAD

**Issue by YoshGit** [elysium-project/server#1021]
This was a previously confirmed issue and a fix has already been attempted, but in-game testing shows that execute (rank 5 at least) is still not triggering chance on hit abilities from the main hand. Similar methodology for testing was used as [https://github.com/elysium-project/server/issues/1011](url) and [https://github.com/elysium-project/server/issues/1012](url) with a large enough sample size.

The previous "fix" can be found here: [https://github.com/elysium-project/server/pull/187/files](url)

**Comment by hckYosh** [comment]
Just did some more testing. While shield bash is proccing main hand correctly, Shield Slam is not.

**Comment by hckYosh** [comment]
A guild mate told me he was not able to find execute or shield slam in his spellicon.dbc but was able to find shield bash with icon id 280. This may explain why the fix seems to work for shield bash, but not for shield slam.

**Comment by hckYosh** [comment]
Evidence that Execute should trigger main hand procs.

If you look closely at approx 9:33, you see two Thunderfury procs occurring back to back. What happens here is a normal main hand swing triggers Thunderfury and then execute triggers Thunderfury within the same second (you can see the second proc the instant his GCD starts after using execute). Because there was no indication of a windfury proc, we can rule out back to back procs due to windfury. Note that because this is in Naxx, Thunderfury procs triggering themselves is not possible.

Source: https://www.youtube.com/watch?v=WMlJWC0Glqw&t

Thunderfury procs do not proc Thunderfury:
https://elysium-project.org/bugtracker/issue/3649
http://wow.allakhazam.com/forum.html?forum=21&mid=1136245524240202932#10

**Comment by hckYosh** [comment]
Just noticed that similar fixes have been proposed but denied. Now that there is indisputable evidence, a similar fix should resolve this problem.

[https://github.com/elysium-project/server/pull/187](url)

**Comment by sknnbones** [comment]
For OP:
[Still-frame of video for evidence](http://imgur.com/a/Wl7Gf)
