### ISSUE TITLE
Blessing of Shahram should scale at 20% spell damage/healing just like Crystal Restore

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#1115]
http://db.vanillagaming.org/?spell=16599 from http://db.vanillagaming.org/?item=12592#wh-comments
"•Blessing of Shahram: Group restore life"
http://db.vanillagaming.org/?spell=15229

is the exact same spell as Crystal restore

(6) Apply Aura #8: Periodic Heal  

https://github.com/elysium-project/server/issues/603 (crystal restore proof)

**Comment by ItsmeAga** [comment]
unlike crystal restore it is casted by the summoned add and not the player. Its unlikely that it still scales with the player's spellpower

**Comment by Mostprovidedlinks** [comment]
Yet the players gear determines the creatures spell coefficient.

**Comment by Imbaslap** [comment]
http://db.vanillagaming.org/?spell=16602
be sure to click on the spell that is procced from the weapon itself before diving head first into nonsense land.

Effect #1	(42) Summon Guardian (10718) 
Radius: 3 yards

which summons this: 
http://db.vanillagaming.org/?npc=10718

under the NPC ID, this NPC has a specific AI that behaves whatever way it is coded to be. (server side coded).

from there, the NPC needs to be scripted to have a set of abilities, when to cast it, etc...

none of that has anything to do with spell power coefficient nor should it.. otherwise your battle chicken and dragon whelpling would have the same benefit.. and it would be broken.
