### ISSUE TITLE
Old Epic Mount Models

### ISSUE THREAD

**Issue by whateversaf** [elysium-project/server#1182]
Old Epic Mount Models are not available anymore, although CM's confirmed there will be a grace period of 1 week!

**Comment by martinjlowm** [comment]
I most certainly hope they won't be. I was lucky enough to get the wolves on my mage yesterday.

**Comment by rasber-3** [comment]
please reintroduce the mounts for a grace period so we can get the mounts we couldnt get without runecloth turn ins

**Comment by qshler** [comment]
Some of us were really counting on that grace period, and planed our schedule accordingly. Please reconsider the grace period, it would mean alot.

**Comment by Mostprovidedlinks** [comment]
please do

**Comment by FireReaver** [comment]
we were assured many times on discord that the grace period would have been granted, also specifically from the 28th onward.

Personally I held myself from buying the BoP epic 60 mounts because I was aiming to get one BoE on this week. If I knew beforehand that this process wouldn't be sure and eventually had to be discussed, I would have bought the BoP I was aiming for at least.

Please, reconsider your last statements, and give us the BoE week, or at least the BoP rare ones so we can finally put our minds at rest.

Thanks and keep up the good work!

**Comment by whateversaf** [comment]
i did pretty much the same as FireReaver, now im mad as hell, please keep your word and bring them back.
