### ISSUE TITLE
[Alterac Valley] Texture jumping exploit.

### ISSUE THREAD

**Issue by deftime** [elysium-project/server#1332]
Hello,
There is one big bug at battleground Alterac Valley - able to get Alliance's base from hills, jumping over textures. This is broke game balance and horde can enter to Aliance's base evade tower, elites and other factors. It was not supposed to be like that! In retail it was not be able.
Please, fix it and back normal balance to Alterac Valley. Thank you.

**Comment by Picajzla** [comment]
back to normal alterac valley in which alliance has obvious advantage? No sane man can deny that alliance base and archer is stronger than horde's? To save you some time im gonna tell you they did say it's allowed and won't be punished

**Comment by WobLight** [comment]
> back to normal alterac valley in which alliance has obvious advantage? No sane man can deny that alliance base and archer is stronger than horde's. To save you some time im gonna tell you they did say it's allowed and won't be punished
Ah, now, have you any fact supporting this? it's indeed the very opposite, Horde have a large number of bottlenecks to stall Alliance, that's quite obvious just looking at map layout. Alliance southern bunker is also very exposed and easy to take.
It's known (and easily verifiable) that Blizzard favoured Horde gameplay in many ways. They have an endless abount of small and big advantages, starting with racials, battleground terrains and so on.

**Comment by KrishiFr** [comment]
> It's known (and easily verifiable) that Blizzard favoured Horde gameplay in many ways. They have an endless abount of small and big advantages, starting with racials, battleground terrains and so on.

sources ?

**Comment by Furnicarium** [comment]
All horde are exalted already so is too late to fix, time to ban.

**Comment by WobLight** [comment]
> sources ?

Isn't reading racial traits enough?
AV would take too much time to explain accurately, let's take arathi that's simpler:
![arathi_vision_fields](https://user-images.githubusercontent.com/26815207/27809397-8edb9918-604f-11e7-9b8b-95272bca57c5.jpg)
As you can see (if you never noticed by just playing AB) Farm + BS + LM are waaaay more easier to defence than any other combination of bases. And since farm is horde side, it's just plain that it's much easier for them to take those.

**Comment by deftime** [comment]
I played the retail in 2006 (last year before BC), and I definitely remember, that Horde NEVER can jump over that hills, they ALWAYS storm over bridge.

**Comment by KrishiFr** [comment]
I didn't ask you about AB, we are talking about AV... Alliance can also jump up the fences, and also I'd like to point that first exalted people were from alliance not horde. If horde weren't doing that alliance will have advantages on AV due to the bridge and you all know it. 
Secondly, GM allowed it they post it on discord many times.

**Comment by WobLight** [comment]
> Secondly, GM allowed it they post it on discord many times.

GM allowed what? Did you even look at the map? ST - BS - GM travel times are at least 20% greater than farm - LM - BS, are you saying that doesn't matter? isn't it a great help for horde? And there's the vision field to take in account, horde is able to camp in the middle of the triangle being able to see all flags, while ST - BS - GM sight field doesn't touch in any useful position. If you can deny that, I don't feel like wasting my time upon a complex BG such AV.

**Comment by KrishiFr** [comment]
WTF you talking about isnt this post about AB ? if you're not happy reroll horde and rage about alliance

**Comment by WobLight** [comment]
Ok now, you say "alliance base and archer is stronger than horde's"
Let's have a look at Horde base main bottleneck (which is not outer fence ofc)
![bottleneck1](https://user-images.githubusercontent.com/26815207/27829967-8520d35a-60c4-11e7-9689-136a9c484ea0.jpg)
As you can see, the tower door is very narrow, and unless you twist your camera a lot, visibility is greatly reduced for alliance.
![bottleneck2](https://user-images.githubusercontent.com/26815207/27830010-a8e88648-60c4-11e7-9ec7-7c9a45252dd1.jpg)
Also, horde caster can easily climb there from towers, which allow them to cast without fear of melee classes been able to attack them.

Also note that both towers have sight almost inside the tower, they're indeed able to shoot at players in the doorway.
The path between the door and the horde inner base is also much narrower than alliance bridge, thus easier to defend.

Additionally, Stormpike GY it's much nearer to the alliance bridge than Frostwolf GY to horde tower bottleneck, thus is much easier for horde to reinforce their front.

**Comment by reinbring** [comment]
Just wanted to add that this "texture jumping exploit" was in fact also there in vanilla WoW and is not considered a bug. There are many places you can wall jump due to the way terrain is made and was never a bannable offense apart from getting into restricted zones (Mount Hyjal). This happens on every private server and the Game Masters have already stated several times that they won't be making any changes to it. Just suck it up and place some mages there to block the Horde! :^)

**Comment by deftime** [comment]
reinbring, did you playing in official vanilla? And I played and I tell again that there WAS NOT this exploit on AV.

**Comment by WobLight** [comment]
Oh BTW, this is a duplicate of #776, there's already a discussion about that here, as Dun Baldar climbing was mentioned in wowwiki in 2008 (not confirmed to be in retail though, dunno when private servers begun to making appearance).

**Comment by WobLight** [comment]
> reinbring, did you playing in official vanilla? And I played and I tell again that there WAS NOT this exploit on AV.

I was playing and I don't recall noticing horde using it, but that they weren't using it doesn't mean that it wasn't there already.

**Comment by KrishiFr** [comment]
Hey as many horde's are already exalted, should we turtle the game ?

**Comment by reinbring** [comment]
@deftime Just because you didn't experience people using the backdoor jump doesn't mean it wasn't there. Yes, I played retail from release and there are several wall jumps available to easily get into the Alliance base, not just the one used right now. At that time it wasn't nearly as used (due to information not spreading as fast, not as tight-knit communities etc. as already mentioned) and it wasn't a real problem people cared about.

Even if it gives Horde somewhat of an advantage you still need enough people to actually make use of it and that's not guaranteed. And it's certainly not worth making a non-blizzlike change by putting an invisible wall there (or whatever solution they would have). You will never achieve a retail-like feel to AV again due to player knowledge, it will stay this way and the best thing you can do to counter it is either defend the back door or be better at rushing than Horde.

**Comment by WobLight** [comment]
> Even if it gives Horde somewhat of an advantage you still need enough people to actually make use of it 

I can assure you that it makes ridiculously easier for horde to take Stormpike Aid Station. Two peoples of any class, without any particular gear or trick can cap it, while for horde side you would need most like some very good geared plate or capable druid/rog players, and it wouldn't be a risk free anyway.

**Comment by thepparker** [comment]
Working as intended. Both factions have numerous places they can skip fortifications by utilizing the terrain
