### ISSUE TITLE
Iron Pommel

### ISSUE THREAD

**Issue by psavery** [elysium-project/server#1525]
For the Raene's cleansing quest where you need to get an iron pommel from the rusty chests that the rotting slimes drop near the Dor'Danil Barrows Den in Ashenvale, the iron pommel isn't dropping for several people (including me) after many, many chest openings.

We think the quest is bugged.

**Comment by brotalnia** [comment]
Tested on development branch and it is dropping. The chance is set at 13%, so maybe you just got unlucky.

**Comment by psavery** [comment]
I abandoned the quest and picked it up again, and then I found it on my first drop.

**Comment by psavery** [comment]
But I had searched probably ~50 boxes and didn't find it a single time before abandoning the quest and picking it up again. So it looks to me that abandoning and picking it up again fixed it.

Someone else said he'd looted a "ton" of them and didn't find it. I never got to tell him that I fixed mine by abandoning it and picking it up again.

**Comment by jcm3** [comment]
This quest is still bugged.  The drop chance for the chest may be 13% but the item contained within should be 100% and that is the issue here, the item is not in the chest.  I have abandoned and picked up the quest twice now and killed over 50 of these things and can not continue this quest chain as a result of it.
