### ISSUE TITLE
T0.5 Quest : Falrin's Vendetta

### ISSUE THREAD

**Issue by ramangan** [elysium-project/server#1541]
According to Vanilla DB, the beads should drop off the Ogres at 80% drop rate. 

http://db.vanillagaming.org/?item=21982

The current drop rate is closer to 2-3% for the beads.

**Comment by Sabre142** [comment]
Drop rate is correct.

db.vanillagaming.org is another private server not a source.

http://web.archive.org/web/20060514010414/http://wow.allakhazam.com:80/db/item.html?witem=21982 Here you can see the drop rate is right at 2-3%.

**Comment by xniko** [comment]
Wouldn't that drop rate be incorrect as well, since only the people on the quest would have had the  chance to get the quest item? Majority of the players weren't on the quest when killing the ogres, therefore the drop chance was displayed lower than it actually was in databases (i.e. thottbot).

If I recall correctly the way data gathering worked back then the info gathering addons couldn't differentiate if you were on a quest or not when recording certain drops. Feel free to correct me on this though.

**Comment by Sabre142** [comment]
If it did track people without the quest I think the drop rate would appear to be much lower.

**Comment by kampeador** [comment]
2%-50% Depends on the mob.

**Comment by starsnstuff** [comment]
Just ran it - 4 drops from a normal DM N non tribute run (3 party members who had the quest, no shared loot i.e. fastest one to loot took the quest item). 

Doesn't seem reasonable as you'd have to run the instance an average of 18.75 times to complete the quest for all three in this case.

**Comment by ramangan** [comment]
Yep. Took me around 8 hours farming the Ogre's out front in the Dire Maul courtyard. This is by far the most painful part of the quest chain.

**Comment by thepparker** [comment]
Drop rates are as intended
