### ISSUE TITLE
[Ancient Petrified Leaf][The Eye of Divinity] not at 100% dropchance yet

### ISSUE THREAD

**Issue by ItsmeAga** [elysium-project/server#1609]
No drops in those two after the patch.
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=81704
http://realmplayers.com/RaidStats/RaidOverview.aspx?Raid=81716

Patchnotes from 1.6 quote: "The chance for an Epic quest item dropping from the Majordomo's chest has been increased to 100%."

http://wowwiki.wikia.com/wiki/Patch_1.6.0

**Comment by Tunesisback** [comment]
hey just gonna hop in here and talk about realmplayers for a bit.  The first question before i get into that though is, were you in either the zeitgeist or the whatever raid which you linked?  I mean to say, can you corroborate, yourself, that the item did not drop because you and 39 of your friends were all there and saw that it did not drop?

Because as a frequent data contributor I can tell you, each of those raids only had 2 people reporting, furthermore with domo's chest in particular, the addon won't detect who got the loot if they aren't near enough to see the "such and such player got [such and such item]" as that message is actually limited to distance like a /say or /yell and is different than other chats like /party or /raid or /guild, or custom channels etc.

So if Slotty/Mortag (who judging by damage taken appear to be tanks) and Mkxvd/Nm didn't wait around at domo's chest to make certain they see who got all the loot, it won't show up on raidstats at all and is not by itself strong evidence for a bug report because of these issues.

But, like I said at the beginning, if you were in one of these raids and can corroborate with multiple witnesses, I'd take that more seriously.

**Comment by martinjlowm** [comment]
Whatever did get a leaf even though it's not listed.

**Comment by thepparker** [comment]
Domo's chest will always have either the leaf, or the eye.
