### ISSUE TITLE
Elysium [Quest] - A Strange Red Key - Bugged

### ISSUE THREAD

**Issue by Enuhal** [elysium-project/server#1623]
After starting the quest "A Strange Red Key" in Felwood, it's currently impossible to interact with the NPC "Captured Arko'Narin", thus completing the quest and starting the next part of the chain. This has been an issue for quite a while.

**Comment by kampeador** [comment]
I've found some bugs with this quest, but I can't reproduce exactly this issue which you mentioned above. When someone starts an escort(quest: Rescue From Jaedenar), gossip and quest giver options are getting removed from the NPC, until event will be failed/finished.
I wonder if someone has completed "A Strange Red Key+Rescue From Jaedenar" quests after server restart. If it is a case, then this issue is easy to solve.

**Comment by Enuhal** [comment]
Well, I've tried to do this quest 3 times in the last couple of weeks; Every time, I was able to open the cage, but not able to interact with the NPC inside. Others I've talked to reported the same issue.

**Comment by Maduse** [comment]
Confirmed. I couldn't interact with the NPC while being on the quest.

**Comment by QAkvastskaft** [comment]
See: #2667
