### ISSUE TITLE
Mindvision NPC bug

### ISSUE THREAD

**Issue by xylaist** [elysium-project/server#1634]
I tested this out in stormwind, I used mindvision on a npc and it registered as me entering combat and spawned SW guards. Immediately after that I leave combat but the guards remain for a certain period of time.

Basically using mind vision on npcs in stormwind (atleast in the cathedral of light) cause Guards to spawn

**Comment by ifyousayso** [comment]
1. Mind Vision resist shouldn't cause agro or combat.
2. The PC debuff should never be resisted (since it make no sense or difference anyway).
3. Target jumping is broken. If casting Mind Vision from one target to another, the second target gets the buff but the camera remains on the first. :(

http://wow.allakhazam.com/forum.html?forum=243&mid=1180492860238167588

**Comment by ifyousayso** [comment]
Mind Vision should be resistable (as far as I can tell here):
http://wow.allakhazam.com/forum.html?forum=243&mid=1180492860238167588&h=50&p=1#20

Two mentions of chain-casting at:
https://wow.gamepedia.com/index.php?title=Mind_Vision&oldid=1586622

.. and #2116 doesn't fix any of the other issues I listed above. Shall I create a new issue?.. or 4 new?

Assuming my first paragraph is correct, #2116 is a hack that adds a bug. :(
