### ISSUE TITLE
UBRS Raid ID?

### ISSUE THREAD

**Issue by Slyman155** [elysium-project/server#1709]
Got in a UBRS group and noticed I was never in the same instance as them, and noticed I have a raid ID for UBRS which doesn't expire for 11 hours, has to be a bug I assume.

**Comment by Neejrow** [comment]
Just encountered this issue on Elysium PvP. It's actually quite serious.

2 people from my guild that were in my UBRS group, were zoned in to a different UBRS. Was a strange bug but that instance happened to have Jed in it. So I gave lead to one of them and asked everyone to zone out and then back in to the ID with Jed.

However when we got to 1st boss. The boss was not there and after we killed the aoe mobs after triggering the event, 1st boss was nowhere to be found. Which meant the doors to the hatchery would not open.

We tried to zone out and reset the instance but it would not reset, nobody that was part of the group was able to reset UBRS to get a new ID. Everyone tried relogging, and using the /script LeaveParty() scripts etc.

I have come to the conclusion that it has something to do with the broken BWL raid ID's this week. Because I zoned into BWL to check and it has completely respawned. Yet my guild killed Nefarian last night. I do not have a BWL raid ID under my raid instances, but I have a Blackrock Spire Raid ID that does not reset for 2 days 21 hours.

Also the people that were  NOT part of my guild in the UBRS group, now are saved to a BWL raid ID for simply zoning in to UBRS.

Something is seriously wrong with Raid ID's on Elysium right now.

**Comment by Galexis-Elysium** [comment]
I was also in this UBRS group and submitted a ticket to a GM. I"m not sure what is causing UBRS to save to a raid ID but I have the blackwing lair id as well, even though i have never been inside. after joining a different UBRS group, i was still locked to the first (broken) one

**Comment by b82a** [comment]
I have the same problem, but with Dire Maul

**Comment by JosipbrozElysium** [comment]
Known issue.

Best regards!
