### ISSUE TITLE
Lakota'mani (q:883) has wrong lvl req

### ISSUE THREAD

**Issue by ifyousayso** [elysium-project/server#1747]
Database says 17, item says 10.

**Comment by Sabre142** [comment]
You need to elaborate way more. Otherwise this is useless.

**Comment by ifyousayso** [comment]
Which part is unclear? Have you even looked at the quest? It starts by using an item. The item says it requires level 10. Whe trying to use it, it fails. In the database, the quest seems to require level 17. Take your trolling to World, please.

**Comment by lovemonkeyz** [comment]
This issue has existed since vanilla. You can even check Wowheads DB. The item says Requires level 10, but the quest requires level 17 to pick up. This issue has existed with all 4 Barrens "Drop quest" items, Lakota'mani, Owatanka, Washte Pawne and Silithid Harvester. This is not a bug with Elysium, but an error made by Blizzard from the start.

I doubt you'll get much assistance here, as changing items to be different from what they were in Vanilla isn't something that should be done.

**Comment by ifyousayso** [comment]
Well if you are correct, then, sure, mark it as invalid.. but please upvote other issues too that are "fixed" here even though they were actual bugs on retail, such as https://github.com/elysium-project/server/issues/1774 .
