### ISSUE TITLE
Nodes dissapearing due to strange/very rough zone border 

### ISSUE THREAD

**Issue by Heyhohohoho** [elysium-project/server#1793]
1. http://i.imgur.com/9xzWSn2.jpg

2. http://i.imgur.com/hr7E06h.jpg

3. http://i.imgur.com/K0KlEPZ.jpg
Coords - approx (39 , 80) western plaguelands

1st pic shows the node right outside border
2nd shows the node right as I cross the border
3rd shows the node has dissapeared by the time I get to it

**Comment by keaarori** [comment]
Seems like an issue similar to https://github.com/elysium-project/server/issues/127

**Comment by ifyousayso** [comment]
Correct me if I'm wrong, but as far as I can recall, there was never any "zoning" outdoors on retail during vanilla.. and probably not TBC either. It almost seems as if the server was made for WotLK, then downgraded to vanilla. Would it be possible to remove this mechanic altogether?

I created a hunter recently and my pet keeps disappearing/reappearing between zones.. it's ridiculous. :|

**Comment by Phoosy** [comment]
The zoning functions are put in to handle the large amount of players per zone, otherwise called 'instancing'. It spreads the core processing out to smaller chunks instead of whole world spaces.

See: https://github.com/elysium-project/server/issues/219 which crosslinks to other issues reported like this.

**Comment by ifyousayso** [comment]
Yes, I realize that, but I never noticed it on retail. Perhaps they had awesome hardware.. or a different solution.

Just thinking: Currently, it seems as if two zones share a border and either a character/node is on one side of the border or the other. Would it be possible to extend both zones by the "client max view distance" so that they overlap and the zone being left doesn't unload until the PC is a bit into the next? That way, by the time the previous zone unloads, everything near the PC would show up properly since they are all in the new zone.. Of course, if the coordinates of a node are outside the zone boundaries, this wouldn't make a difference.

I haven't looked at the project at all, so this is only in my ignorant head.

Happy coding.

**Comment by Heyhohohoho** [comment]
The man above has a completely moot idea of what he is talking about.

**Comment by Phoosy** [comment]
It wasn't on retail as retail servers weren't designed to handle over 3k people regularly, let alone the 8k-10k peaks that Elysium is hitting.
