### ISSUE TITLE
Rested Status

### ISSUE THREAD

**Issue by Phatcat** [elysium-project/server#1811]
No rested status while being online and at an inn.
No rested statud while being offline and not at an inn.

Yes, you would slowly build up rested while online and in town/at an inn or offline and not at an inn (just at a much slower rate)

**Comment by lovemonkeyz** [comment]
Incorrect on the Offline outside Inn part. I just logged on a character who never entered an inn and it has rested xp. Although, I stood still in UC and according to the script below I gained no rested xp. I logged out for approx 2 minutes and gained 24 rested XP. On my level, 474 XP is 1% xp, you gain 5% every 480 minutes, or 1% every 96 minutes. 474/96 = ~4,9 xp rested per minute (I'm pretty baked, my math might be way off :D). This leads me to believe the script I'm using doesn't update values properly if you're online. I'm sure someone else can think of better testing to prove this to be true, since 4.9 * 2  = 9,875 xp. So either I gained more XP than I'm supposed to offline, or the script can't update the rested XP value without relogging. 

So I went on, and from the moment I ran the script the last time (approx 3 min after it was at 314 XP), relogged and log back on instantly. I had accumulated 2 xp in that relog period. I ran the script again after 3 minutes, showing no xp gain, relogged and logged back on instantly and yet again it showed 2 xp gain.

So something is off with online xp gathering, at least. 

Double checked with: 

`/script p="player";x=UnitXP(p);m=UnitXPMax(p);r=GetXPExhaustion();if -1==(r or -1)then t="No rest."else t="Rest: "..(math.floor(20*r/m+0.5)).." bubbles ("if r+x<m then t=t..r else t=t.."level +"..(r+x-m)end t=t.."XP)"end;DEFAULT_CHAT_FRAME:AddMessage(t)`

> One bubble of rested XP (5% of a level) is earned for every 8 hours spent resting. A maximum of 30 bubbles (150% of a level) may be earned. In other words, you can leave your character resting in an inn or capital city for up to 10 days (without gaining experience) before you earn the maximum amount of rest state, and a resting character stores up one full level of rest in 160 hours (6 days, 16 hours).

> You also become rested while logged off in the wilderness, but the accumulation is slower. When logged off "outside," rest is gained at a quarter of the rate in an inn, or one bar every 32 hours.

Source: http://vanilla-wow.wikia.com/wiki/Rest


![charwhoneverenteredinn](https://user-images.githubusercontent.com/26850364/28746893-aac7ba46-7493-11e7-97f2-f71872a128ee.PNG)
![restedoffline2min](https://user-images.githubusercontent.com/26850364/28746892-aac5b656-7493-11e7-823a-f55520970eea.png)
![offlinelessthan1second](https://user-images.githubusercontent.com/26850364/28746894-aac94eec-7493-11e7-903b-770912790836.png)

**Comment by thepparker** [comment]
Players should gain rested experience while online inside a rested area

**Comment by Phatcat** [comment]
Indeed as thepparker says, this can also be seen in joana's leveling videos; just pick one where she is visiting Orgrimmar and you'll notice that after she's been in town for a few moments she gets the 'you feel rested' message in her log and the bar changes to blue, in real time.

**Comment by blubba22** [comment]
I am like 99,9% sure that being online in an inn/capital city gave you a rested bonus once on the servers. Must have become bugged some time along the way.
