### ISSUE TITLE
Questitems

### ISSUE THREAD

**Issue by xtomatex2** [elysium-project/server#1843]
When you have a group, the questitems are free for all

**Comment by Ripper007** [comment]
This is not a bug, this is the way they quest items worked in Vanilla. Blizzard changed that in The Burning Crusade expansion.

**Comment by xtomatex2** [comment]
okey thx :)

**Comment by Phatcat** [comment]
> This is not a bug, this is the way they quest items worked in Vanilla. Blizzard changed that in The Burning Crusade expansion.

... This is not true.

That is not how quest items worked in vanilla, they were not free for all, they followed the rules of round robin.... 

http://wowwiki.wikia.com/wiki/Loot?oldid=291936 (from 2006)

> Quest Loot: Quest loot is on a seperate loot distribution and there are two common modes for this to occur. 1) In quests where the party is to collect one of a specific item from a specific mob (Collect the head of (mob name here)) then regardless of loot setting, the mob will indicate lootable by every party member with the quest (and without the object). Each member may loot the quest item off the corpse. The other loot on the corpse is subject the the party loot setting. 2) In other quests which require collecting several items of a type (harpy feathers for example), the quest items will drop on some mobs and be looted in the normal way, except that if the current looter can't collect the items (not on quest, already has full set) then the quest loot is FFA for those members who can still pick up the quest items. Other items on the corpse are goverened by the party loot setting. On some quests the quest loot is always free-for-all and this may be the above mechanic gone haywire. Some quests where the party is collecting one item will use the named mob mechanism (1). ( the Shaman Voodoo Charm from The Sleeping Druid quest, for example, where all party members can get the charm off the same shaman )

Let's take the important part out of that;

> 2) In other quests which require collecting several items of a type (harpy feathers for example), the quest items will drop on some mobs and be looted in the normal way

I am so tired of seeing people simply guess on stuff here. Yes, quest item loot is bugged. Money is bugged too. Money is following round robin, where money was always free for all (since it's always shared equally nomatter the loot type)

@xtomatex2 please re-open this issue and @Ripper007 next time bring proof of your invalid claims.

**Comment by Phatcat** [comment]
Okay since you clearly won't, I am going to re-open this....
