### ISSUE TITLE
Hunter gets in combat when pet does after being ordered to attack

### ISSUE THREAD

**Issue by ifyousayso** [elysium-project/server#1892]
It should not. It should, however, get in combat if the pet is already in combat with something and an order is issued. Same goes for warlocks and demons..

https://www.youtube.com/watch?v=FaV6oAteJGI&t=2h54m34s
https://www.youtube.com/watch?v=FaV6oAteJGI&t=3h24m48s

**Comment by sipertruk** [comment]
These videos disprove the issue.

**Comment by ifyousayso** [comment]
For those with working eyes and brains, the hunter gets in combat once it attacks, not when the pet does.

**Comment by sipertruk** [comment]
First video, no the target switch happens before the pet reach the target, the hunter enter in combat when the pet's first hits land, before the first ranged attack.
Second video, what raptor strike the button doesn't even flinch, when the hunter enters in combat he's showing his back to the target and running away, he starts ranged attacks after.
Third video the delay is very short it could be due to latency, also in this video you can see the combat indicator stuck at 2h40m, it's not really accurate.

Here you can see the hunter gets in combat while casting bandage on himself and chatting : https://www.youtube.com/watch?v=FaV6oAteJGI&t=2h54m
also a lot of examples in this one : https://www.youtube.com/watch?v=9Sh4k3rAZSE

**Comment by ifyousayso** [comment]
You know what? I think you're right.

Most moments still look weird (as in the hunter gets in combat after a certain update and not due to an action), but that bandaging disproves my report. Thanks for looking it up - I appreciate it.

Sorry for wasting your time.
