### ISSUE TITLE
[Code] Missing development on-boarding from repository readme

### ISSUE THREAD

**Issue by luigimannoni** [elysium-project/server#2039]
**Issue:** I would love to help further in the project and be in the position to successfully compile, run and test my PRs.

At the moment the Readme in the root of the project doesn't provide a development on-boarding guide: 

- What are the prerequisites for setting up a local development environment?
- Should I use a specific IDE/coding tool?
- How do I seamlessly compile the project?
- Do I need third party software to run on my machine required to run Mangos? (eg: mysql)
- Is there a specific Vagrant/Docker/Virtualbox image/solution that helps the tasks above?
- How do I test specific things in-game? (eg: link to a list of GM commands)

**Comment by martinjlowm** [comment]
I had the same thought a few months ago. I never got around to actually writing anything though, since I wanted to have all tools compiling on MacOS first... and the project really does need some refactoring in many ways.

- External dependencies are as follows: MySQL, ACE, OpenSSL, TBB and CMake.
- Any IDE works. I use Emacs and I have a `.dir-locals.el` that I can share at some point. It sets up indentation, include path for CMake and more.
- The two main daemon binaries are realmd and mangosd. The `CMakeLists.txt` in the root folder has everything set up for those. I suggest to create a `build` directory and execute `cmake ..` therein.
- MySQL has to be running, yes, and no more than that.
- I don't know of any virtualization images. The thought has hit me once or twice though :)
- There is no such list as far as I know. What I do, is browse the source code for commands`src/game/Chat/Chat.cpp` contains chat command tables you can look at. Dumping this to a README should be desirable.

**Comment by JosipbrozElysium** [comment]
Agreed. We will soon start filling up the repo's wiki with useful pages.

Until then, you can use this guide from CMANGOS: https://github.com/cmangos/issues/wiki/Installation-Instructions

Best regards!
