### ISSUE TITLE
Nazjak Spawn Timer is not Blizzlike

### ISSUE THREAD

**Issue by Tunzer** [elysium-project/server#2194]
Current Behavior: Nazjak Spawn time is around 24 hours, it could a little more (26) or a little less (22) and has consistently (past 3 spawns) spawned before the 32 hour minimum.

Correct Behavior: Nazjak will spawn between 32-48 hours after he was killed.

**Comment by martinjlowm** [comment]
His spawn time is dynamic.

**Comment by Tunzer** [comment]
Current Behavior: His Spawn timer is Dyanmic

Correct Behavior: He's a rare spawn who shouldnt be flagged for dynamic spawntimes

**Comment by Manlet** [comment]
Blizzlike timers were not meant for a population over triple the side.

Benediction quest npc timer and Rhok'Delar quest demon timers are also faster and not blizzlike, you know why? Because it suits a larger population better and stops congestion at these npcs/quests.

It's also an intended feature by the devs, see: https://forum.elysium-project.org/topic/24778-development-update-12152016/

> Several important rare spawns now benefit from dynamic respawn rates.

**Comment by Tunzer** [comment]
Thanks, thought it was a bug- thanks for the context.
