### ISSUE TITLE
Spirit of Zanza and Blasted Lands buffs don't stack

### ISSUE THREAD

**Issue by ohganot** [elysium-project/server#2197]
Only the +25 Stamina buff from Blasted Lands shouldn't stack with Spirit of Zanza. All others should.
I couldn't find video evidence on this, but its very clear that they should stack due to a number of reasons.

1) Buffs with different stats always stack. For example Elixir of the Mongoose and Elixir of Fortitude. It makes no sense that +50 stamina and +25 strength don't stack.

2) Buffs with big differences in durations always stack. Zanza lasts 2h, Blasted Lands buffs last 1h. For example DM +200 AP buff and Winterfall Firewater or Mighty Rage Potion and Elixir of Giants.

3) They are located in different zones and zone specific buffs generally stack with each other. For example Songflower, Rallying Cry, Spirit of Zandalar, DM Buffs, Jujus, etc.

4) There was no evidence that they shouldn't stack #275 "This was updated a while ago but if there's any evidence that it's incorrect (quite possibly is), that would be appreciated" - StadenElysium. Therefore we should go with logic and follow general buff stacking rules. A buff that gives stamina should stack with a buff that gives strength.

Please help me find evidence for this or simply fix it to be in union with the rest of buff stacking rules!

**Comment by fgsfdss** [comment]
On this subject, based on a comment on thottbot Lung Juice Cocktail should give +50 stam instead of +25 until 1.11: https://web.archive.org/web/20060407225314/http://www.thottbot.com:80/?i=6228

Comment confirming patch change: https://web.archive.org/web/20070303204527/http://www.thottbot.com:80/?i=6228

**Comment by fgsfdss** [comment]
On this subject, these items should give +50 to their respective stats instead of +25 until 1.11: https://web.archive.org/web/20060407225314/http://www.thottbot.com:80/?i=6228
https://web.archive.org/web/20060222234625/http://www.thottbot.com:80/?i=5175
https://web.archive.org/web/20060314032014/http://thottbot.com:80/?i=6261
etc

**Comment by blubba22** [comment]
I would open a new issue with the wrong stats since these are two different issues. 
I sure do hope they fix both.

**Comment by GuybrushGit** [comment]
>You can use them with a diffrent BL buff. 
>I.e. I stack the health one with the agi BL buff for rag
>https://web.archive.org/web/20070314082028/http://www.thottbot.com:80/i20079
