### ISSUE TITLE
Some wrong quest level requirements for Un'Goro.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#2274]
All the crystal quests (ids 4381, 4382, 4383, 4384, 4385, 4386) should require level 47 instead of 53.
http://wowwiki.wikia.com/wiki/Quest:Crystal_Restore and the rest are the same.

Muigin and Larion quests should all require level 47 (quest ids 4142, 4143, 4144 for alliance, and 4145, 4146 and 4147 for horde).
http://wowwiki.wikia.com/wiki/Quest:Larion_and_Muigin
http://wowwiki.wikia.com/wiki/Quest%3AMuigin_and_Larion

A lot of chains are broken because you can't attain the quests only 5 levels after they were designed as.

**Comment by Sirael11** [comment]
According to http://web.archive.org/web/20060110074828/http://wow.allakhazam.com:80/db/quest.html?wquest=4381 the crystal quests do not have a level requirement at all, they just need the quest 4321 to be completed. I did also check 4384 which is the same so i guess all are the same.

For the Muigin and Larion quests the wayback machine gives other results:

4141: 48, http://web.archive.org/web/20050826093224/http://wow.allakhazam.com:80/db/quest.html?wquest=4141

4142: 49, http://web.archive.org/web/20050827152212/http://wow.allakhazam.com:80/db/quest.html?wquest=4142

4143: 50, http://web.archive.org/web/20050528220851/http://wow.allakhazam.com:80/db/quest.html?wquest=4143

4144, no level, http://web.archive.org/web/20050224141346/http://wow.allakhazam.com:80/db/quest.html?wquest=4144

4145, 47, info is from 2007 though, older archives dont list a requirement, http://web.archive.org/web/20070618051839/http://wow.allakhazam.com:80/db/quest.html?wquest=4145

4146, 48, same problem as above, http://web.archive.org/web/20071002020222/http://wow.allakhazam.com:80/db/quest.html?wquest=4146

4147, 47 in 2006, http://web.archive.org/web/20060526122002/http://wow.allakhazam.com:80/db/quest.html?wquest=4147

4148, only seems to require 4147 completed, http://web.archive.org/web/20071022040416/http://wow.allakhazam.com:80/db/quest.html?wquest=4148

No idea how the values in the db are atm though. Horde level requirements are mixed because the quest id's are mixed too, so that 4146 is the follow-up of 4147.
