### ISSUE TITLE
Blessing of Might should increase ranged attack power

### ISSUE THREAD

**Issue by BrynjaDarrow** [elysium-project/server#2323]
Okay, this is an issue that's not that clearcut, but imho Blessing of Might should give ranged attack power.
Let's start the argument with the fact, that Blessing of Might gave ranged attack power from patch 1.0 to 1.10 ( http://wayback.archive.org/web/20060616111020/http://thottbot.com:80/?sp=19838 ). It was then changed to melee attack power only in 1.11 (http://wayback.archive.org/web/20060622175909/http://www.thottbot.com:80/?sp=19838 ), but that change was reverted in 2.03 ( http://wowwiki.wikia.com/wiki/Patch_2.0.3 [see Paladins] ).

So, an overview: 
1.0 -> 1.10 ranged & melee AP
1.11 -> 1.12 melee AP
2.0 -> ranged & melee AP

So for the majority of vanilla (and directly afterwards), Blessing of Might gave ranged and melee attackpower.

I think either changing Blessing of Might from melee to ranged & melee permanently, or changing the spell from ranged & melee to melee only with patch 1.11 like it was in vanilla, so that hunter can enjoy Blessing of Might at least in MC, BWL and AQ.  It's not like hunters are overpowered with 1.12 talents.

**Comment by kev41** [comment]
Can't change talents/spells as far as I know, they are in the client 1.12.1

**Comment by Dasharius** [comment]
It would concern me a lot if any spell values are hard coded into the client because of hackers. As far as I know, only the tooltips for spells and talents are integrated into the client. The client receives all Itemtooltips and spell values from the server. It is also the server who calculates your damage and everything. Would be very bad if done otherwise. So for this one, a simple SQL Aura_Ranged_AP would do the trick, while the in-game tooltip would still state melee AP.

This surely is a debatable fix, but like Brynjadarrow said, Hunter's aren't anywhere near overpowered with 1.12 talents. I can remember that the difference between Warriors/Rogues/Mages <-> Hunters wasn't that big back then like we experience it today with optimized raids and Tanks that are able to create enough threat for this level of Rogue/Warrior/Mage DPS. Blizzard nerfed Hunter (and Rogue) a lot back then. Today we see that in case of hunter it was quite overdone and like Brynja stated, Blizzard reversed this change 5-6 months later.

Always remember that Blizzlike isn't Blizzcopy, a lot of things already got changed on purpose in favor of a better blizzlike experience because you can't recreate the player knowledge and playstyle of people back then.

**Comment by Phibs77** [comment]
Similiar to "Rallying Cry of the Dragonslayer". It says "Attack Power" but it doesn't add any ranged AP, even when the tooltip doesn't explicitly say "Melee Attack Power". Every other item with "Attack Power" also adds RAP, so why should this buff not add RAP?

**Comment by fgsfdss** [comment]
Spells and talents are 1.12.

**Comment by Phoosy** [comment]
The general philosophy is that spells, mechanics, etc. should operate at their 1.12.1 values. There have been some seemingly odd deviations from this philosophy and it's not clear what QA considers standard operating procedure anymore but take that for what you will.

Considering the tooltip explicitly calls out melee attack power only in the client version, having it deviate would be rather confusing.

**Comment by thepparker** [comment]
Spell mechanics are 1.12 where feasible for gameplay purposes. The only exceptions to this are some item spells which cannot be replicated due to client changes, in which case we have made minor modifications to have them more like their pre-patch counterparts (BRE, ZG potions, etc).
