### ISSUE TITLE
Don Julio's Band can DROP from NPCs in AV.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#2373]
http://db.vanillagaming.org/?item=19325#dropped-by
This is clearly an error which should be remediated asap.

**Comment by QAkvastskaft** [comment]
Steps to test:

.debug loottable creature 13218 1000

**Comment by ohganot** [comment]
Many of the loottables have errors in them. Seems to be a stock mangos issue, since db.vanillagaming.org also has these. For example:

http://db.vanillagaming.org/?npc=7431 drops Thorium Ore and Dense Stone.
http://db.vanillagaming.org/?npc=11659 drops Wildvine Potion.

There are countless drop table errors like this, somebody simply needs to go over every single drop table and correct them.

**Comment by Cabro** [comment]
Just curious: does the alliance equivalent of this NPC also have his sell items into his loottable? There are 4 NPCs that sell AV items, with IDs: 13216 -> 13219.

**Comment by Maduse** [comment]
As a matter of fact the other 3 has completely empty loot tables so this is something to look into.
