### ISSUE TITLE
Loot range should be increased

### ISSUE THREAD

**Issue by BrynjaDarrow** [elysium-project/server#2410]
Atm the range in which you have to be to a boss to be able to loot him during raids is too small. This can make it impossible for people to loot the boss after he is downed, just because they were out of range.

Example:
If your mages move away during the mage classcall for example and Nef then dies, he may be impossible to loot for them. Doesn't matter if you are dead or alive btw. 

I reckon the range, in which you are eligible to loot should at least be as large as the largest bossrooms.

**Comment by malekoydaerb** [comment]
Seconded

Last night Intoxicated (anathema alliance) killed Ouro. Instance ID 405. Was a messy kill but a kill none-the-less with 25 deaths. Roughly 15 of those 25 were unable to receive loot form Ouro, despite them being in his room, because of range from him when he died. I was killed by a sweep right before he did his last submerge and when he came back up, was on the other side of his room. Because of that range, I was unable to even view loot on him, let alone receive anything via masterloot.

I have never in all my years playing wow, even on other buggier private servers, encountered this issue. As well, it's not just Ouro, I have personally seen it occur on bosses in UBRS(Drakkisath), MC(Garr and Rag), Ony, and BWL(Nef). 

Players should not be penalized, and total lack of loot is a huge penalty, for simply having the bad luck to die within the bosses room, but further than 40 yards from the boss.

**Comment by Cabro** [comment]
To be honest, if you were active in a boss kill in a raid, then it shouldn't matter where in the whole instance you are, when the loot popups you should get the popups also. Same for Master Looter, you should be in the assign menu.

**Comment by malekoydaerb** [comment]
@Cabro if you release, you are not in the instance, and thus dont get loot. that is a known thing and not an issue, your fault for releasing. the issue we're describing is coming about when you are present for the boss, helping kill it but dying during the fight before said boss, and being far away from the boss when he dies and thus not getting any loot. 

my direct experience last night had myself and about 10-15 others unable to see any loot on the boss. as well, the loot master was unable to send anything to us and was getting an invalid target error when they tried.

**Comment by yankopetrov** [comment]
We had the same problem with Nef. Couple of raiders died in phase 1 and they was unable to loot later.

**Comment by Cabro** [comment]
@malekoydaerb I said i wasnt sure about the case where you release and then someone loots afterwards, but as for being alive in the instance just not within 20 yards or so of the corpse, it is definitely a bug. You could open chests from bosses, loot bosses with you being in the other side of the instance and you would STILL get the loot popups. This is the correct behavior which should happen.

**Comment by BrynjaDarrow** [comment]
Why was your commit closed, Guybrush?

**Comment by BrynjaDarrow** [comment]
Okay, I see now. Yeah this change is even better.
Keep up the good work!
