### ISSUE TITLE
Tranquility is broken and cancels during channeling in many cases: CONFIRMED

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#244]
BUGGED BEHAVIOR
Tranquility Rank 4 = http://db.vanillagaming.org/?spell=9863

"Regenerates all nearby group members for 294 every 2 seconds for 10 sec. Druid must channel to maintain the spell."

This channeled spell cancels as soon as someone runs out of the effect (~25 yards) or if someone dies.

Demonstration of the bug: https://vimeo.com/205681056

 CORRECT BEHAVIOR
Tranquility should not cancel if someone runs out of the effect or if someone dies. Instead, the affected person should just lose the buff and the druid continues channeling.

 SOURCES
http://db.vanillagaming.org/?spell=9863

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/2671

**Comment by WobLight** [comment]
Tranquility is not recognized as AoE spell, thus channel is interrupted when the target looses the aura.
There are at least two ways of fixing this:
1. Adding an entry for tranquility in the database, setting TARGET_ALL_PARTY_AROUND_CASTER_2  
*the effect of tranquility itself is gaining an aura, so that could be debated*
2. Check if the AuraHolder is AoE
  *it may have impact on other spells, fixing or breaking them*

**Comment by QAkvastskaft** [comment]
Fixed: https://forum.elysium-project.org/topic/43686-development-update-05042017/
