### ISSUE TITLE
Thunderfury sword proc chance is not blizzlike. (Must be 20%)

### ISSUE THREAD

**Issue by neale111** [elysium-project/server#2456]
Thunderfury is currently still bugged with a low proc chance of around 5-10%. Proven bug in anathema. I won't have to provide any screenshots because the current item script is surely wrong. 

Thunderfury should have 20% proc rate. 
It also has no limitation because it is a not ppm.

All sources from 2005 provides 20% proc rate and has been unchanged even until now in retail, thunderfury still has a 20% proc rate. All sources anywhere in the web from 2005 provides 20% proc rate,  it is the truth anywhere you look. 
Real sources wowwiki, blizzard retail forum, wowhead comments, 2005-2017 posts on thunderfury proc rate, all information provides 20% proc rate so it is unquestionable and undeniable.

However some people's preference and opinion which are basically false claims, they want 5-10% but that figure is non existent on any source and it is non existent on retail as well. 

Thunderfury proc rate is never below 20% in retail wow from 2005 up to now.

There is only one fix and that is to change the item script to 20% proc rate which is the retail value from 2005 to 2017. All real sources provide 20%.

Thanks

**Comment by Mostprovidedlinks** [comment]
2 months ago the proc chance was very good. Was it changed?
Yes it should be 20% if it isnt. It was first 25% then they nerfed it to 20%

**Comment by neale111** [comment]
Currently it is at 5-10%. So it is bugged.

**Comment by Mostprovidedlinks** [comment]
@thepparker can you confirm if this weapon is currently 20%?

**Comment by Mostprovidedlinks** [comment]
That is terrible. It shouldnt be that low.

**Comment by Mostprovidedlinks** [comment]
Prot PalliesPosted: May 24th 2007 8:36am\| IP: Logged \|  Reply to this
--
By: SenzoMuramasa Score: Decent  Link to this post | What this weapon is intended for now after BC is actually quite simple. Warriors -Protection -Fury Paladins -Protection Rouges no longer need as of all the gladiator stuff, hunters....god invented guns and big pets for a reason, arms warriors your too busy with your big fancy swords, ret and holy comon now two handed is the way to go xD. Another fact was after reading after patch history i have come to find it was not nerfed unless there was something i missed. Yes threat generated went down, yes it became one handed (not really a nerf lol) but truely i think the nerf was an illusion created by the expansion, with all these new weapons it would make thunderfury seem useless but in truth it is not. The proc effect is from 20-25% chance to activate so that means 1/5 or 1/4 swings will generate its proc (statistic wise) and that means well in a Prot pally hands we can utterly slow them down, give them massive damage on top of other things as well. Combining with Crusader Seal we will attack faster meaning proc will trigger more.

**Comment by Mostprovidedlinks** [comment]
Stated in vanilla in 1.10

The blade in action is indubitably the best 1H weapon currently (as of patch 1.10) in the game, to a large degree due to the proc. According to the guild Immortality on Skullcrusher (and demonstrated in videos) the proc rate is about 30%, in effect adding almost 100 nature to each hit. This proc works on almost all mobs including Molten Core and Blackwing Lair bosses, with the exception of certain mobs and bosses in The Temple of Ahn'Qiraj that are immune to nature damage. Keep in mind that Thunderfury's proc was indirectly nerfed in 1.9 so that this proc didn't give a chance for another proc, therefore reducing the number of times this weapon activates. This weapon will not proc as much as it did prior to 1.9.

**Comment by Mostprovidedlinks** [comment]
Perhaps it was 30% and was nerfed to 25%

**Comment by neale111** [comment]
Still it must be fixed to 20%.
30% was the proc rate in the early patches which was likely not implemented even in nostalrius.
But in retail and all sources 20% has never been changed ever since.

**Comment by neale111** [comment]
It has been set to the figures 15%, 10% and 5% which are all wrong. 

The correct value is 20% and all real sources provide it.

**Comment by Mostprovidedlinks** [comment]
I agree.

**Comment by neale111** [comment]
Still not fixed. Currently bugged at 5-10% in anathema.

Fix to 20% proc chance, the true proc rate on all real sources.

**Comment by Mostprovidedlinks** [comment]
https://github.com/elysium-project/server/issues/2582

Proof showing it should be 25% in 1.12
