### ISSUE TITLE
Pally Judgement debuffs stacking working on retail finally found proof but the other tread is closed so had to make a new one.

### ISSUE THREAD

**Issue by corrupteddrake** [elysium-project/server#2495]
Edit: Some people are not understanding this post.  This post is about the Confirmed Issue of multiple Pally Judgement debuffs of the same type but different ranks.  This post proves that this was a part of the game on retail and not a bug on elysium.

Hello, sorry to bring this up yet again, but I played a paladin in wow vanilla retail and so I knew paladin judgement debuffs stacking worked on retail vanilla.  I was not going to say anything about this issue because I had no proof either way besides my own memory and it seemed that it would not be confirmed as a bug with theloras defending it so well.  However, m-laniakea locked the tread and even without sufficient proof Confirmed Issued it.  So, recently I decided to look through EVERY raid video from 2005-2006 that I could find to see if I could find this even once happening.  (This was an exhausting and time consuming endeavor I assure you)  And I in fact did finally find proof of this occurring during this time and it must have not been well known at the time because I looked through many many videos and it only happened one time that I could find.  Since m-laniakea said to never bring up this issue again unless someone finally finds new proof either way, I feel that I have not only the right but the duty to bring this up again.

The video is [20 Paladins in ZG](https://www.youtube.com/watch?v=7G4jGG_aeI8)
Published on Dec 31, 2006 

If you watch the video it seemed as if to confirm what Imbaslap said since if there are 20 paladins on the mobs why do they not always have multiples stacks on everything.  However, at the time of exactly 4:42/10:53 the mob they are fighting has TWO judgement of the crusader on it.  This could have only came about if someone in the raid used a lower rank since before this time and later in the video we never see this occurring again. You may have to pause the video at that time to see it because it was only there for a second or two.  I feel that this is sufficient proof that multiple judgments of different ranks occurred during 1.08-1.12 and definitely after it in 2.0.1 and that it was not well known since you would have seen it in more raid videos if it was.

On 5 December 2006, patch 2.0.1 came out.  You may believe that the video was taken a over year before that in patch 1.7 and just never put up until that time, since this was in ZG and everyone I could see is wearing t2 or lower and the main character is using the Zin'rokh, Destroyer of Worlds, which you get off Hakar.  However, the seal and judgement animations are not the ones used in patch 1.7 but one in patch 2.0.1 and on the test server for patch 1.13 (this was for patch 2.0.1 but they called it patch 1.13 while testing)  Therefore, this video was definitely taken after patch 2.0.1 or on the patch 1.13 test server due to the seal and judgement animations, even though the main character does not have crusader strike on his bar (don't ask me why he didn't have that). Even though you can tell that he has the Ret talent Vengeance.(Although throughout the video you can see the main character is a terrible player since he is using mouse click the whole time for his spells, so he must have just sucked so bad he didn't get it)  This makes it impossible for this video to have been before patch 1.8.  I do not think it was on the test server since many people had different gear, but it would explain how they got 20 paladins together and why the main character sucked so bad at playing a paladin.

This is a link to a video showing off the new seal animation for patch 1.13 (2.0.1) on the test server.  [Seals & Judgements in WoW 1.13](https://www.youtube.com/watch?v=LxLfBiTMyGQ)

If you want to see the old animation to see the difference you can just make a paladin on elysium and look or you can look at the animations in the naxx ret paladin video [Insane Paladin DPS](https://www.youtube.com/watch?v=rXNWvytYbyo)

Now we can say we have definitive proof that this is not a bug. 

Q.E.D.

**Comment by Mostprovidedlinks** [comment]
Wow very very good.

**Comment by Mostprovidedlinks** [comment]
I assume this would only be working with paladins and no other classes.

**Comment by Mostprovidedlinks** [comment]
Very good finds. I will read them to see if its legit.

**Comment by Mostprovidedlinks** [comment]
Very very good finds. Good job.

**Comment by Mostprovidedlinks** [comment]
It already said on old forums that paladin can stack wisdom light and crusader
This should be doable in vanilla and tbc.

This is nothing related to rank 1 and rank 2 wisdoms or same rank of same judgements that cant stack together

**Comment by Mostprovidedlinks** [comment]
If elysium isnt allowing wisdom light and crusader to stack together its wrong.

**Comment by Mostprovidedlinks** [comment]
It already said on old forums that paladin can stack wisdom light and crusader
This should be doable in vanilla and tbc.

This is nothing related to rank 1 and rank 2 and rank 3 etc of thesame judgements that cant stack together

If elysium isnt allowing wisdom light and crusader to stack together its wrong.

**Comment by Mostprovidedlinks** [comment]
Even if the video is in tbc it does not matter.

This point is. Old 2006 comments in vanilla say wisdom and light and crusader stack as long ad there are 3 pladins and have never ever been stated not to.

What imbaslap was referring to was rank 1 rank 2 rank 3 rank 4 rank 5 etc wisdom stacking.
Which seems is not possible due to this video you show.

**Comment by Mostprovidedlinks** [comment]
If the 3 arent stacking I hope they end up fixing it.

**Comment by Mostprovidedlinks** [comment]
Its working as of on anathema. seal of wisdom and light are stacking. Crusader should be able to stack too

**Comment by GuybrushGit** [comment]
This again? We already knew of the JotC bug. Judgement stacking is an exploit.

**Comment by Mostprovidedlinks** [comment]
@Guybrushgit

At the moment judgement of wisdom light and crusader are stacking on anathema.
Its proven this is no bug.

You must be talking about stacking different ranks of judgements which is an exploit.

Stacking 3 different judgements isnt an exploit

**Comment by Mostprovidedlinks** [comment]
@GuybrushGit

At the moment judgement of wisdom light and crusader are stacking on anathema.
Its proven this is no bug.

You must be talking about stacking different ranks of judgements which is an exploit.

Stacking 3 different judgements with 3 paladins isnt an exploit

Stacking rank 1 judgement of light with rank 2 judgement of light is.

**Comment by Mostprovidedlinks** [comment]
Hmmm I didnt read this part.
However, at the time of exactly 4:42/10:53 the mob they are fighting has TWO judgement of the crusader on it.

**Comment by Mostprovidedlinks** [comment]
Also this video is from tbc. They are using righteous fury.

**Comment by Mostprovidedlinks** [comment]
Im actually not sure if this is a bug or not.

**Comment by Mostprovidedlinks** [comment]
Their guild is order of the dragon

**Comment by Mostprovidedlinks** [comment]
Their guild is order of the dragon

Also this video is from tbc. They are using righteous fury.

**Comment by Mostprovidedlinks** [comment]
Also this video is from tbc. They are using righteous fury.

**Comment by corrupteddrake** [comment]
This is not during TBC. 
TBC came out on January 15, 2007 and this video was published on Dec 31, 2006.  Therefore, it could not have been during TBC.  
The reason for this post is that during patch 2.0.1 you were allowed to have multiple Pally Judgement debuffs of the same kind but different ranks.  And that the way elysium allows it right now is not a bug and therefore should not be considered a Confirmed Issued of being a bug but a part of the game, because we have never been able to prove that people could do this after patch 1.7.

**Comment by Mostprovidedlinks** [comment]
EU-Shadowsong 

All the paladins are from that server
mcmuff from the guild Radient moon
Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild wave of heroes

**Comment by Mostprovidedlinks** [comment]
EU-Shadowsong 

All the paladins are from that server
mcmuff from the guild Radient moon
Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Order of light

**Comment by Mostprovidedlinks** [comment]
The scary part is I think you are right. Wowcensus is saying they did it in september 2006

**Comment by Mostprovidedlinks** [comment]
Ok here is what it shows.

All the paladins are from the server EU-Shadowsong 
mcmuff from the guild Radient moon
Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Aftermath

**Comment by Mostprovidedlinks** [comment]
http://www.warcraftrealms.com/charsheet/39459458

It was done december 27 2006

**Comment by Mostprovidedlinks** [comment]
Ok here is what it shows.

All the paladins are from the server EU-Shadowsong 

Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Aftermath

  

http://www.warcraftrealms.com/charsheet/39459458

It was done in december 2006 you are correct. Before January.

**Comment by Mostprovidedlinks** [comment]
Ok here is what it shows.

All the paladins are from the server EU-Shadowsong 

Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Aftermath

http://www.warcraftrealms.com/charsheet/39459458

It was done in december 2006 you are correct.

**Comment by Mostprovidedlinks** [comment]
http://www.warcraftrealms.com/charsheet/4132757

**Comment by Mostprovidedlinks** [comment]
Ok here is what it shows.

All the paladins are from the server EU-Shadowsong 

Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Aftermath

http://www.warcraftrealms.com/charsheet/39459458

It was done somewhere in december 2006 and probably on the upload date you are correct.

http://www.warcraftrealms.com/charsheet/4132757
http://www.warcraftrealms.com/charsheet/3254702

**Comment by Mostprovidedlinks** [comment]
But it shows tbc spells. Doesnt that mean it would of been ptr?

**Comment by Mostprovidedlinks** [comment]
Yes they were in 2.0.1 true. So it did exist in 2.0.1

**Comment by Mostprovidedlinks** [comment]
Ok here is what it shows.

All the paladins are from the server EU-Shadowsong 

Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Aftermath

http://www.warcraftrealms.com/charsheet/39459458

It was done somewhere in december 2006 and probably on the upload date you are correct.

http://www.warcraftrealms.com/charsheet/4132757
http://www.warcraftrealms.com/charsheet/3254702

And in the other judgement stacking ony video the rank judgements show increase in damage.
And this all shows in 2.0.1

The problem is how can we find out if it was in one patch under?

Also I think people assuming that we didnt see it in naxx or vanilla is not a good example since paladins
Were not used often to dps and not many were used in melee.

**Comment by Mostprovidedlinks** [comment]
Ok here is what it shows.

All the paladins are from the server EU-Shadowsong 

Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Aftermath

http://www.warcraftrealms.com/charsheet/39459458

It was done somewhere in december 2006 and should be patch 2.0.1

http://www.warcraftrealms.com/charsheet/4132757
http://www.warcraftrealms.com/charsheet/3254702

And in the other judgement stacking onyxia raid video the rank judgements show increase in damage.

The problem is how can we find out if it was in one patch under?

Also we cant assume that it didnt exist because we didnt see it in naxx or vanilla which is not a good example since paladins were not used often to dps and not many were used in melee.
One guild literally had 1 ret paladin.

**Comment by corrupteddrake** [comment]
We already had proof that this occurred during 1.7 and on, but someone found someone saying that they thought it was discontinued on 1.8 and on.  However this shows that it was still occurring in 2.0.1  While I agree that it is not 100% proof that it occurred during 1.12 because they could have gotten rid of it for one patch and then brought it back.  I find this to be very unlikely and the best explanation is that it was there in 1.8-1.12 as well.

**Comment by Mostprovidedlinks** [comment]
Ok here is what it shows.

All the paladins are from the server EU-Shadowsong 

Parcival from the guild radient moon
Hamerkop from the guild wave of heroes
Backup from the guild Aftermath

http://www.warcraftrealms.com/charsheet/39459458

It was done somewhere in december 2006 and should be patch 2.0.1

http://www.warcraftrealms.com/charsheet/4132757
http://www.warcraftrealms.com/charsheet/3254702

And in the other judgement stacking onyxia raid video the rank judgements show increase in damage.

The problem is how can we find out if it was in one patch under?

Also we cant assume that it didnt exist because we didnt see it in naxx or vanilla which is not a good example since paladins were not used often to dps and not many were used in melee.
One guild literally had 1 ret paladin

So we can confirm

1. It did exist in 2.0.1 and onwards and was nerfed in the later tbc patch
2. It wasnt a visual since the onyxia video shows a damage increase

3. All thats needed: Did it exist in 1.12 Drums of war?

**Comment by Mostprovidedlinks** [comment]
One way of finding out would be to message all of the players in that video and ask them on retail or perhaps ask that youtube video.

**Comment by Mostprovidedlinks** [comment]
One way of finding out would be to message all of the players in that video and ask them on retail or perhaps ask the owner of the youtube video. Better yet get someone from the elysium staff to ask.

**Comment by Mostprovidedlinks** [comment]
I do find it odd that it would exist from early vanilla up to 1.7 only to be fixed in 1.8 to 1.12 only to reappear again in 2.0.1 to 2.4

**Comment by Mostprovidedlinks** [comment]
That sounds very very odd.

**Comment by Mostprovidedlinks** [comment]
I do find it odd that it would exist from early vanilla up to 1.7 only to be fixed in 1.8 to 1.12 only to reappear again in 2.0.1 to 2.4

I find that very very odd

**Comment by Mostprovidedlinks** [comment]
do find it odd that it would exist from early vanilla up to 1.7 only to be fixed in 1.8 to 1.12 only to reappear again in 2.0.1 to 2.4

I find that very very odd and hard to believe.

**Comment by Mostprovidedlinks** [comment]
I do find it odd that it would exist from early vanilla up to 1.7 only to be fixed in 1.8 to 1.12 only to reappear again in 2.0.1 to 2.4

I find that very very odd

**Comment by Mostprovidedlinks** [comment]
I do find it odd that it would exist from early vanilla up to 1.7 only to be fixed in 1.8 to 1.12 only to reappear again in 2.0.1 to 2.4

I find that very odd and hard to belive

**Comment by Mostprovidedlinks** [comment]
Another way would be to see if any changes to judgement of the crusader had been made in 1.7 compared to 1.8 and see if it matches the change done in 2.4 to see if the person was telling the truth.

**Comment by Mostprovidedlinks** [comment]
One way of finding out would be to message all of the players in that video and ask them on retail or perhaps ask the owner of the youtube video. Better yet get someone from the elysium staff to ask.

Also. I do find it odd that it would exist from early vanilla up to 1.7 only to be fixed in 1.8 to 1.12 only to reappear again in 2.0.1 to 2.4

I find that very odd and hard to believe

**Comment by Mostprovidedlinks** [comment]
There is a good chance it could of been in 1.12. I think we just need to find a 1.12 video and this will be settled.

**Comment by Mostprovidedlinks** [comment]
One way of finding out would be to message all of the players in that video and ask them on retail or perhaps ask the owner of the youtube video. Better yet get someone from the elysium staff to ask.

Also. I do find it odd that it would exist from early vanilla up to 1.7 only to be fixed in 1.8 to 1.12 only to reappear again in 2.0.1 to 2.4

I find that very odd and hard to believe which means it could exist.

**Comment by Lorilay2** [comment]
This is the same jotc 3% hit debuff stacking on top of someone else who doesn't have it that you have seen in every other 2.0+ video up until it was fixed. As was mentioned in the last bug report, it desperately needs evidence from _before_ 2.0.

**Comment by Mostprovidedlinks** [comment]
QuoteReply

#5Oct 09 2005 at 2:50 AMRating: Decent

Cathela

Scholar

961 posts

Multiple paladins can stack different ranks of the judgements on the same mob. The last time my raid group killed Ragnaros we didn't have enough priests to do AoE heals on the rogues, so the three paladins in the melee groups coordinated different ranks of Judgement of Light on him, and the rogues and dps warriors ended up healing themselves a lot. 

There's also a weird effect where Seal of Fury pushes the proc rate of Judgement of Wisdom way up. It seems like you get two or three times as many procs from JoW if you have SoF running, and sometimes you'll see two or three procs for a single swing. This does not work for Judgement of Light however. 

Also, I think weapon procs can trigger a JoW proc, so if you have a weapon with a proc, you could proc JoW on the regular swing and on the weapon proc. 




#7Oct 13 2005 at 12:31 PMRating: Decent

Cathela

Scholar

961 posts

Quote:

Multiple paladins can stack different ranks of the judgements on the same mob. The last time my raid group killed Ragnaros we didn't have enough priests to do AoE heals on the rogues, so the three paladins in the melee groups coordinated different ranks of Judgement of Light on him, and the rogues and dps warriors ended up healing themselves a lot.


Reportedly this was nerfed in the 1.8 patch so that now you can only have one rank each of JoW and JoL on a monster, though I haven't had a chance to confirm this. 

Also, there's apparently some kind of aggro screwup when JoL and JoW proc since the patch. Not sure if this has been hotfixed or not.

**Comment by Mostprovidedlinks** [comment]
Looks like it exists before 2.0.1

He says it was claimed to be nerfed but he never did find out or confirm it himself.

I find it unfair to confirm his second post when he didnt confirm it.

This means his second post is inadmissable.

**Comment by Mostprovidedlinks** [comment]
@lorilay2 Looks like it exists before 2.0.1

He says it was claimed to be nerfed but he never did find out or confirm it himself.

I find it unfair to confirm his second post when he didnt confirm it.

This means his second post is inadmissible.

**Comment by Lorilay2** [comment]
If it was the actual judgement stacking instead of a bugged icon, why are there only two judgements of the crusader icons on some of the mobs, and never more or any other judgements?

**Comment by Lorilay2** [comment]
Everything you are quoting has been addressed in the previous bug report. This is a duplicate report and should be closed @GuybrushGit

**Comment by Mostprovidedlinks** [comment]
I am not related to the poster of this issue.

http://paladinsucks.blogspot.com.au/2005/12/super-mana-regen-is-back.html?m=1

This shows it is back in 1.9

**Comment by Mostprovidedlinks** [comment]
This means 1.9 it existed and 2.0-2.4 existed.

**Comment by Mostprovidedlinks** [comment]
This means 1.9 it existed and 2.0-2.4 existed.
This means your reason for not allowing it is based off it didnt exist in 1.10-1.12. 3 patches.

**Comment by Mostprovidedlinks** [comment]
Sorry but 3 patches is very transparent.

Also if they were merely icons we wouldnt see a damage increase in the 40 man onyxia video.

**Comment by corrupteddrake** [comment]
This is not meant to be a duplicitous post.  It is meant to show new evidence to a closed post.  There was a lot said in that other post.  If you do post on this tread, please do not bring up any info that has been already said in the other tread.  Also please don't spam this tread with the same post over and over again Mostprovidedlinks.  While I love any new info you can bring please don't do that.

**Comment by thepparker** [comment]
https://www.youtube.com/watch?v=7G4jGG_aeI8 4:42. Consecration is ticking for 58 and 72 on two different mobs (58 on the add, 72 on the boss). The extra add dies, he switches back to the main target. 

We see two JotC icons. One JotC falls off yet Consecrate is still ticking for 72. TL;DR Multiple ranks of JotC do not stack their effect, even if there was a bug that visually allowed multiple debuff icons to be up at once. 

"Q.E.D" as you succinctly put it.

**Comment by Mostprovidedlinks** [comment]
@thepparker Looks like I was wrong. Great find thepparker
