### ISSUE TITLE
[Elysium] The Captain's Chest (Horde)

### ISSUE THREAD

**Issue by lovemonkeyz** [elysium-project/server#2590]
Seem to be unable to pick up The Captain's Chest from Captain Hecklebury Smotts. Unable to find any data on when it was added, except for Wowhead stating "Added in patch 1.11.1.10772". 

According to https://github.com/elysium-project/server/issues/1624 , thepparker states it was added in a later patch, however I don't believe this to be true. According to https://www.reddit.com/r/ElysiumProject/comments/60fa1l/elysium_captains_chest_belt_from_mokrash/ they can be picked up by Alliance, but not Horde.

**Comment by Sirael11** [comment]
I would agree with thepparker. While it is no proof the quest was added on the old database on Jan 4th, 2006 (see: http://web.archive.org/web/20060416014639/http://wow.allakhazam.com:80/db/quest.html?wquest=8551). This coincides with the date of the 1.9 patch which was released Jan 3rd, 2006. Patch notes don' state it thought.

The alliance version (http://web.archive.org/web/20040622131855/http://wow.allakhazam.com:80/db/quest.html?wquest=614) has been present since the start of the game. You can also see this from their quest ids where the alliance version has 614 and the horde version 8551 (stating that it was added much later).

**Comment by lovemonkeyz** [comment]
That would make a lot of sense. I only played alliance during early retail so that's why I was so god damned sure that I'd done the quest prior to these patches, but if the horde one was added later it it definitely makes sense it's not there now. If I had an alliance char I'd check if the quest is actually present.

**Comment by GuybrushGit** [comment]
Both sides will be available once progressive database is implemented.
