### ISSUE TITLE
Minning wont lvl

### ISSUE THREAD

**Issue by ikillforcash** [elysium-project/server#293]
So my minning is lvl 100/150 only thing i can mine to get lvl is tin ore (yellow atm) next is iron ore at lvl 125
problem is when i mine tin ores i dont get lvl

**Comment by slacker3007** [comment]
That seems to be fine. unless something is wrong with proc rate.
http://www.blizzardguides.com/wow_mining_guide.html
"The leg from 100-125 is also pretty bad, as Tin is green at this stage and therefore your getting skill ups at fewer intervals (just pray its a Silver spawn, instead of Tin, as this will still be yellow to you). "
"Easiest way to level up to 125, is to go to The Wetlands and find Thelgan Rock (its near the entrance to Dun Algaz - 53,64 for those with location addons)."

**Comment by sknnbones** [comment]
To comment, I have leveled my mining to 228.

I did the above method as well, you can mine Incendicite Ore at 75 mining skill, and it stays yellow until 90 mining skill. You can use this all the way up to 125 I believe, tin and silver both spawn in the cave mentioned above. 

As a note, if you have any +mining enchantment or gear, remove it as it can cause you to hit "green/yellow" for ore level 5 whole levels sooner than without. I only use those enchants if I am below the required level to mine an ore, otherwise I keep them off.
