### ISSUE TITLE
Warlock Summon spell targeting does not work correctly.

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/server#295]
Switching target during the process of summoning someone changes the summoning target. The summon spell should summon the current target when the summoning spell is actually started. Switching target after should not matter at all.

**Comment by aeranadots** [comment]
Have also noticed this, the summoning animation is also not working for me. When players click the summoning portal, they should start channeling until enough players have clicked it, iirc.

**Comment by kevmodrome** [comment]
Yep! That's not as irritating as not being able to switch targets though :)

**Comment by kakysha** [comment]
This bug becomes a bigger problem when you have some addons that inspect players on mouseover over players, for example to add additional info into tooltip. Because inspecting internally causing target change, so when you summoning target and hover your cursor over another players around you - your target is changed and summon is fked up. It becomes almost impossible to summon anyone if you are in raid with 40 ppl around you :)

**Comment by GuybrushGit** [comment]
I could not find the spell that triggers the channel animation for the players that click it. Anyone knows what is it?

**Comment by sipertruk** [comment]
Maybe it's "arcane channeling" 23017.

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/47461-development-update-24052017/
