### ISSUE TITLE
Onyxia/nef buff should have cooldown (Rallying Cry of the Dragonslayer

### ISSUE THREAD

**Issue by knasen88** [elysium-project/server#297]
Current behavior:
Players can turn in the Head of Onyxia and Head of Nefarian in, and receive a buff, even if the head of those monsters are already displayed on a pike (already been turned it recently).

Intended behavior:
While Onyxia's head is on a pike in Orgrimmar, it should not be possible to get a buff from https://vanilla-twinhead.twinstar.cz/?quest=7491 (horde version)
While Onyxia's head is on a pike in Stormwind, it should not be possible to get a buff from https://vanilla-twinhead.twinstar.cz/?quest=7496 (alliance version)

While Nefarian's head is on a pike in Orgrimmar, it should not be possible to get a buff from https://vanilla-twinhead.twinstar.cz/?quest=7784 (horde version)
While Nefarian's head is on a pike in Stormwind, it should not be possible to get a buff from https://vanilla-twinhead.twinstar.cz/?quest=7782 (alliance version)

Source:
http://alt.games.warcraft.narkive.com/nbkesSJ1/turing-in-onyxia-head-turnin-city-buffs
21. jun. 2006
When I have handed-in Onyxia's head, nobody was buffed,
because a head already dangled from a stone ridge on the
entrance to Stormwind (valley of heroes). I don't know
how often it is removed, but I've heard that only one head
can be handed-in per week.
Not at all! It's a couple of hours normally (or is that 24h? can't
remember), check the guards to see what buff they have, this will let
you know if your head will buff everyone around.
AFAIK* you can get the buff only every six hours. But the buff (and the
head itself) are only two hours. But I think Nefarians head is on a
different counter; but you can't receive the buff more than once.
http://wowwiki.wikia.com/wiki/Patch_1.7.0
Fixed a bug that was preventing Rallying Cry of the Dragon Slayer to fire when Onyxia's head was turned in (assuming a head was not already up).

**Comment by PlaskED** [comment]
So would that mean Onyxia and Nefarian heads are on 2 timers with 6 hour CD?

Where is the information about the heads not being able to be up in SW and OG at the same time?

Wowwiki isn't a credible souce I could go in there right now and edit it.

**Comment by knasen88** [comment]
patch 1.7.0 isnt a credible source?

https://web.archive.org/web/20070602172347/http://www.worldofwarcraft.com/patchnotes/patch-05-09-13.html satisfied?

**Comment by PlaskED** [comment]
Ah I see, I thought you meant that alliance couldnt buff when horde had head up, vice versa..

"Fixed a bug that was preventing Rallying Cry of the Dragon Slayer to fire when Onyxia's head was turned in (assuming a head was not already up)."

Question is now, what is the CD on the Nef and ony timer? 6 or 24h? Warchief got 6 hour, so I guess something similiar?

**Comment by knasen88** [comment]
I may have sounded salty yes, but I thank you for your criticism because it did improve my report, I'm just tired of Horde being cuckolded on every project when given chance to.

Kronos tried putting a CD on onyxia because "Muh Blizzlike" but it backfired completely, I hope Elysium realises this and remove BOTH cooldowns.

**Comment by Tunesisback** [comment]
I signed up for github just for this.  In regards to the source about the cooldown, i'm very skeptical that this is accurate at all.

from: http://alt.games.warcraft.narkive.com/nbkesSJ1/turing-in-onyxia-head-turnin-city-buffs#post9

> AFAIK* you can get the buff only every six hours. But the buff (and the
> head itself) are only two hours. But I think Nefarians head is on a
> different counter; but you can't receive the buff more than once.
> 
> * I haven't stood around for 6 hours and tried to hand in the head etc.
> 
> Urs

This guy is speculating that it's 6 hours, and makes it clear that he hasn't tested the 6h time frame.  This poster, Urs, also states that you can't recieve the buff more than once, which I'm certain is false.  Since he's stated one false item and has 1 speculative item I don't think he knew what he was talking about.

Nothing I see in the twinstar links suggest a 6h internal cooldown, or otherwise suggests a duration of the onyxia/nefarian head monument in org/sw.

There are indications in that newsgroup archive that the buff can't be received while the monument is spawned (http://alt.games.warcraft.narkive.com/nbkesSJ1/turing-in-onyxia-head-turnin-city-buffs#post3), I really think that the newsgroup archive comments about a 6h despawn is a very weak source.

I'm going to repost this comment on the other relevant issue.
