### ISSUE TITLE
Black Dragonscale Gear

### ISSUE THREAD

**Issue by Skgabedy** [elysium-project/server#3180]
With release of ZG patch, it appears that the Black Dragonscale Gear is not reflecting any set bonuses.

**Comment by jalle2** [comment]
Can confirm reep

**Comment by sadfx** [comment]
Stop making false reports. Just because something isn't the same doesn't mean it used to be right and is now wrong. They fixed the items.

**Comment by Asexual** [comment]
This is bullshit I quit Elysium until they are transparent about this shit.

**Comment by jalle2** [comment]
The black dragonscale gear receives set bonuses in patch 1.8 and should never have had set bonuses before that. But since many fury warriors use the set for the extra %hit and are now below hit cap due to the fix is arguable. I personally think that the set bonus should not have been removed but i am a fuey warrior so lel

**Comment by jalle2** [comment]
You can read about it here: "Patch 1.8.0 (2005-10-10): The Black Dragonscale Leatherworking Armor pieces are now parts of a set and have set bonuses so they should be significantly more desirable" https://wow.gamepedia.com/Black_Dragonscale_Boots
