### ISSUE TITLE
[Hunter] Devilsaur tooth trinket does not work with some abilities

### ISSUE THREAD

**Issue by lequintal69** [elysium-project/server#354]
http://db.vanillagaming.org/?item=19992
Use: Your pet's next attack is guaranteed to critically strike if that attack is capable of striking critically. (cooldown 2 min)

This works for normal attacks.
This works for Bite/Claw

BUT

It does NOT work for :
-lightning breath
-thunderstomp
-Screech

those abilities are direct dmg spells and they can crit, so they should be affected by that trinket aswell.

**Comment by sknnbones** [comment]
Maybe the claw/bite "spells" are flagged as melee attacks?

I believe, and from reading guides and comments, this trinket is supposed to only work on basic attacks:

People mention it can be blocked/parried ("spells" cannot be blocked or parried)

People mention quite often pairing it with prowl for the bonus basic attack dmg

Every mention of it in vanilla guides use "attack" while referring to pet skills as "abilities" None of the guides talk about pairing the trinket with a ranged spell casting pet (like Wind Serpent)


The spell effect itself:

**(6) Apply Aura #52: Mod Crit Percent 
Value: 100**

**Comment by lequintal69** [comment]
Found that
http://wow.allakhazam.com/forum.html?forum=243&mid=116459097452217837

" Actually, if your pet has bite/claw or another damaging spell, one of them will crit along with its normal attack at the start of a fight! So if timed right, it could be 3 or 4 crits in a row!! "

So i guess it works with all the damage abilities

**Comment by sknnbones** [comment]
I don't think that is reliable information:

He is responding to someone saying you can apply the buff and it was expire ever until you attack, so you can get two crits in a row by popping the trinket, waiting for cooldown to refresh, attacking, and then popping the trinket after the first crit.

The post says you can crit 3-4 times in a row, which makes no sense as the buff does not stack, and two would be the max you could do as the second cast would reapply the 2-min cooldown


I'd take the strategy from the guy with 1,500 posts over a wierdly worded post that makes no sense based off the items cooldown and only 50 posts on that account.

**Comment by lequintal69** [comment]
http://wow.allakhazam.com/forum.html?forum=243&mid=116429963282555298
Look at that:

_And the reason I chose to give one up in frenzy is because I have the Devilsaur Tooth (thanks to Sayis for this one). And something most people don't know about the tooth is that it causes your pet to crit 2 times. One of the crits is with its normal attack, and the second crit is with bite (or claw). The reasoning for why it does this as far as I can tell is because the pet probably does a normal attack and the spell bite/claw simultaneously, so it crits twice. So using the tooth, I only have a 1/25 chance that my pet will not have frenzy proc at the start of a fight_

**Comment by sknnbones** [comment]
Seems like a bug TBH.

The item specifically states the next attack, and even the poster states its because bite/claw activate at the same time as basic attack.

Also no mention of any other abilities outside of melee focus dump skills "Bite" and "Claw", so as those are working the same here as on vanilla retail, we still have lack of evidence as to whether or not ranged pet "abilities" should trigger the item.

**Comment by sknnbones** [comment]
Seeing how Blizzard simply changed how this item worked :

Patch 2.0.3 (09-Jan-2007): "Devilsaur Tooth" now grants your pet crit rating instead of a guaranteed crit.

Makes me believe that the trinket should never have applied to Claw/Bite and they simply couldn't stop a pet from casting those abilities and attacking at the same time, so they gave it crit rating instead.

As far as I know, in Burning Crusade, crit rating and spell crit rating were seperate stats.

As for bite/claw, I believe they pop the trinket due to being melee ranged physical dmg based "special" basic attacks.

**Comment by GuybrushGit** [comment]
Spell data for Primal Instinct says it procs on:
02 Successful melee attack
04 Successful attack by Spell that use melee weapon

So ranged attacks should not proc it. Screech is melee thought so there might be a bug there.

**Comment by sknnbones** [comment]
The tooltip say melee, but the spell detail say 5 yards (Combat Range)

**Comment by GuybrushGit** [comment]
Tested this, Primal Instinct is working properly with melee abilities.
