### ISSUE TITLE
[Exploit]: Item dupe

### ISSUE THREAD

**Issue by Kittnz** [elysium-project/server#379]
Item dupe exploit has not been fixed in the public core.

**Comment by PlaskED** [comment]
Well, whats the point? Its a anticheat measure. Shouldnt be public

**Comment by Kittnz** [comment]
Item duping shouldn't be allowed and should be fixed core wise? This isn't really an anti cheat measure in my eyes. More of a bug fixing?

**Comment by PlaskED** [comment]
Ofc not, but if they push their fix the exploiters can use it to work around it.

I don't see why this fix is needed on open source when all it will lead to is help the cheaters.

**Comment by Kittnz** [comment]
The core should be exploit proof for such things. It's prolly just a bad check somewhere or the container system does not work correctly. Again this is open source and those fixes to the container system should be in the core here. I understand they would keep their anti cheat branch private for the movement etc.. but this is a core issue.

**Comment by brotalnia** [comment]
Whoa, shots fired! That's quite a jump in logic you made there. I don't like arguing, but you're kinda dragging me into this. Releasing the fix for the exploit is going to prevent cheating, not help cheaters. If it is indeed a bug in MaNGOS, then other projects like mangoszero and cmangos would implement it immediately, and so would every serious server out there. Keeping it in the dark is what enables cheating. Look at what happened with namreeb's authentication bypass. He posted it and boom, in 24 hours its fixed everywhere. There are even cheaters in the thread that are angry at him for posting it.

Having such an exploit is a major flaw in the core, which discourages people from using it, which in turn leads to less people possibly contributing. I thought we were trying to do something more here than fix bugs on Elysium. What i want is to there to exist an emulator that is as close to perfect as possible and available to everybody. Isn't that the whole point of making the project **open source**? To advance emulation?

And not get too off topic, but calling ownedcore a cheating forum is a gross simplification. It's a forum for people who like to tinker with games. The guides and tutorials section is more than twice the size of the exploits forum. I have an interest in all things WoW and collect pretty much everything related to it. Currently my emulators collection is up to 41,191 files.

**Comment by StadenElysium** [comment]
The authentication exploits (plural, because there were two) from Chaosvex/Daemon/Namreeb weren't fixed within 24h of release. It took over five months for a good chunk of servers to get around to patching it.

Having said that, the hotfix will be added to the repo in the next few days.

**Comment by Kittnz** [comment]
I guess https://github.com/elysium-project/server/commit/a9384c35e0c99140ae9edff3c15b6cc805425d13 
is not the fix you guys made and is for another dupe exploit.

**Comment by ryancheung** [comment]
I thought Elysium public core had fixed this one already... 

@Kittnz There're still few item dupe exploits, as far as I know, but I've no idea where are they.
Player in my server report to me there is still some guy do item dupes after this fixes in old mangos core before migrated to Elysium core, I'd know if Elysium public core had fixed that.

**Comment by Kittnz** [comment]
Any update on this @StadenElysium  ?

**Comment by sknnbones** [comment]
@Kittnz a9384c3 seems to be a fix for people modifying packets to loot items, but the items not destroying from the container after being looted.

From what I could find out on the forums + IMGUR gallery, that most current dupe seemed to allow a much wider array of items to be duped, which would seem to rule out items looted from creatures being duplicated.

**Comment by ryancheung** [comment]
@sknnbones Thanks you for mentioning wrapping paper, we should remove all of them from the core, in case of item dupe.

**Comment by StadenElysium** [comment]
https://github.com/elysium-project/server/commit/451f7c0f762dfada34c5f9b0a729e084991cd060
