### ISSUE TITLE
Fix for loot randomization

### ISSUE THREAD

**Issue by RussianE39** [elysium-project/server#42]
Please import patch from cmangos tree:
https://github.com/cmangos/mangos-classic/commit/4c60c50a836f72f79bce8e132dc0be92871bcac9?diff=split

**Comment by elysium-duks** [comment]
I'll create a pull request with this update. Looks solid.

**Comment by PlaskED** [comment]
Don't you need to seed before using `random_shuffle`? It will always yield the same result.

**Comment by FractalCabush** [comment]
"When provided, the function gen determines which element is picked in every case. Otherwise, the function uses some unspecified source of randomness." Id say it would be wise to use the <random> library to pick a suitable random number generator that can be passed as an argument to random_shuffle()

**Comment by FractalCabush** [comment]
I think this should be bumped and discussed further, having proper rng is vital to the game

**Comment by StadenElysium** [comment]
Haven't forgotten about this. :+1:

**Comment by RussianE39** [comment]
or forgotten ? :)

**Comment by thepparker** [comment]
Makes no difference to loot outcomes
