### ISSUE TITLE
Consecration doesn't scale with spell power.

### ISSUE THREAD

**Issue by sovs** [elysium-project/server#587]
Consecration should take a 33% benefit from spell power. It doesn't.

**Comment by theloras** [comment]
it's 33% of spell damage but then divided by 8 for each tick over the 8 second duration

**Comment by sovs** [comment]
That's true Theloras. I should have specified but that's what I meant. I tried with 120 SP gear and no difference than with 0 SP. With 120 SP the 8 second damage of R5 Consecration should be 384*1.33 = 510.72, 510.72/8 is 63.84 per tick. But it still does 48 per tick (base 384/8).

**Comment by ryancheung** [comment]
I tested this before and can confirm that the coefficience applys properly.

**Comment by killerduki** [comment]
I agree with @sovs  and have discussed about this long time ago with Jakira .

@theloras  it does indeed work 33% with Spell Damage but here it is the problem that is not working properly . 

I will paste the whole conversation from Jakira and me regarding this issue because i am lazy to explain it over again : 

Jakira - 03/09/2017
@here
I NEED YOU
You are the ultimate Paladin that I know of

Killerduki - 03/09/2017
lol
i am lazy cat :wink:(edited)

Jakira - 03/09/2017
being serious :3
lol
Because I can't get a dev or qa person at the moment
and I don't have a paladin
is consecration scaling properly with SPD or not
on Anathema

Killerduki - 03/09/2017
"technically" it work correct, but not blizzlike

Jakira - 03/09/2017
how so?
and please
go into detail

Killerduki - 03/09/2017
well let say it scale properly 33% like it suppose to , but "Tick" does not "Variate" damage according to "let say extra 1 damage or 3 damage" , instead they wait for "extra 8 damage" for all 8 ticks (that was example) , otherwise it is not counting it properly
I will try to get you video how it work in retail
1 moment to find the video

Jakira - 03/09/2017
with a bonus of 44 SPD, i should get 1-3 bonus dmg on each tick of consecration
wait
wait
it does scale
but on enormous amounts
+44 damage increases only 1 dmg per tick
that is weard
i thought id increase by 2
is what someone has been yelling at me for
saying it doesnt scale

Killerduki - 03/09/2017
That's what i said, it should not be "Fixed damage"
Currently either "full 33%" or doesn't add at all
Ill give you an example
with 30 Spell Damage , it will give you 8 damage (while 2 damage is wasted) , it should instead 1st 2 ticks to give extra 1 damage and then the rest tick should give "the rest of the damage"

Jakira - 03/09/2017
is that how it's supposed to be?

Killerduki - 03/09/2017
with 30 spell damage it should be like this : 50 - 50 - 49 - 49 - 49 - 49 - 49 - 49

Jakira - 03/09/2017
and right now, it just gives all the damage on the last tick?

Killerduki - 03/09/2017
Instead it work like this :  49 - 49 - 49 - 49 - 49 - 49 - 49 - 49  (2 damage wasted)

Jakira - 03/09/2017
hmm

Killerduki - 03/09/2017
It is not big issue tho
so you should have currently 60 spell damage in order to get "50 - 50 - 50 - 50" ...(edited)
In reality , it should be "sensitive" on how much spd
just moment , trying to find the video
here it is , i will give another video too in case you can't see properly

https://www.youtube.com/watch?v=84OwHLAuQzc
At 1:00 you can see during "Consecration"
sometime his consecration tick 55 , sometime (rarely) tick 54
(try to use google chrome and html to slow the speed) so you can see easier the  numbers
Same at 6:25 (precisely at 6:29-6:30) it will show  you sometime 51 and sometime 52 damage
per tick

This is thanks to the "Spell Damage"
if you have 10 spell damage, (from original 48 damage) you should have first 3 ticks doing 49 damage while the rest 5 ticks (or randomly) do 48 damage . (this was example)
This was video from Vanilla player but was posted in youtube in 2007

Here is another example from TBC player
https://www.youtube.com/watch?v=9WWOU1X1lqI
This is another TBC Video
00:15 , you can see consecration sometime tick 73 and 72 randomly
"the spell damage" variate

Jakira - 03/09/2017
hmm

Killerduki - 03/09/2017
As i said , it is not huge issue
But not blizzlike

Killerduki - 03/12/2017
did you got your answer  regarding consecration ?(edited)
Few things regarding consecration that doesn't work "blizzlike"
In retail when you cast consecration , the first tick should interrupt the "capturing flag" in bg (only first tick when cast) , this nobody bother to investigate neither they know about it
Second thing , the 1st tick in retail (you can see in videos) did the damage immediate upon the cast, in server currently it wait for like 1/5 second before tick , and mobs usual avoid (which is bug and not mention)
not huge issues, but still bugs :wink:

**Comment by killerduki** [comment]
@theloras  just to add , Consecration is not only ability that should work like that "variate damage". 

It is also SoR (fixed already)
It is also Holy Shield (not fixed,neither reported)

**Comment by GuybrushGit** [comment]
Every single ability in the game should work like that, if something does 10.5 damage then there should be 50% chance of doing 10 and 50% chance of doing 11. But implementing something like this would take a ton of work, don't expect it in the near future.

**Comment by killerduki** [comment]
@GuybrushGit  that's why i didn't bother reporting this known bug, since it is required huge amount of work , for something which is not 100% important, but good to have it fixed.

**Comment by thepparker** [comment]
Consecration currently scales correctly, however there is no chance to round on ticks. There is a PR pending for this behaviour
