### ISSUE TITLE
Crystal Restore should scale for 23% per tick with healing/spell damage in vanilla

### ISSUE THREAD

**Issue by Mostprovidedlinks** [elysium-project/server#603]
Jamaz of the Shadowmoon from retail vanilla is in patch before 1.9 and he appears to be wearing Lawbringer chestplate and lawbringer belt which is +40 healing. (He has only 40 healing on him)
He is using http://db.vanillagaming.org/?item=16434 http://db.vanillagaming.org/?item=16435 
due to before patch 1.9. Rank 9 holy light also didn't exist.
He claimed he is not geared "The opponents are more heavily geared and skilled, the editing is much more refined etc so he couldn't have had marshal
http://www.warcraftmovies.com/movieview.php?id=9026

Jamaz with lawbringer Chest and lawbringer belt as seen https://www.youtube.com/watch?v=VbYnyfaL7J8&t=26s

He has darkmoon maelstrom 1:54 and insignia of the alliance is on cd 2:32 used in his videos showing so he would not have had any healing trinkets. No healing weapons, no weapon healing enchants, no healing cloaks since his cloak is reddish and gold outlined and matches not one healing and spell damage cloak on aowow http://imgur.com/a/TZGBt

Now crystal restores normally ticks 134 
http://db.vanillagaming.org/?spell=15229 
As you can clearly see in the video, his crystal restore is ticking 143 compared to the normal 134
https://www.youtube.com/watch?v=kr_GlmzQ_M4&t=5m48s patch is prior to 1.9 in description

You can clearly see the date title that this retail paladins videos were posted
Fist of the Heavens by Jamaz. 2005-10-24
http://www.warcraftmovies.com/movieview.php?id=9026
http://www.warcraftmovies.com/pv.php?t=3&l=Jamaz
http://www.warcraftrealms.com/charsheet/712512 

The crystal restore should scale and benefit 9 healing on each 3 second tick for every +40 healing/spell damage you have. which is 23% coefficient.

Reply to GuybrushGit  
1. he couldn't possibly have the spell damage Lieutenant Commander's Lamellar http://db.vanillagaming.org/?item=23277 due to him being in 1.8 the latest and prior to AQ. He would have http://db.vanillagaming.org/?item=16436. He is also not rank 12 marshal gear since it makes no sense for him to be using lawbringer. 

What about healing from Zg enchants?
The problem is theres a suspicious reason he might have not of had zulgrub sigil enchants is because this video was RELEASED only 1 month after ZG was released. 
Pld Jamaz IV - Fist of the Heavens  by  Jamaz  
2005-10-24
He would of had to reach exalted too so I doubt he had them by then.

Now here is the main proof that he had only 40 healing:
Retail Jamaz paladins holy light rank 8 were 1330, 1401, 1312 and 1382 heals, he couldn't have rank 9 holy light in 1.8. With Holy Light rank 8 he is doing:
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=5m19s (1401 heal)
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=6m31s (1312 heal)
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=4m38s (1382 heal)
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=3m13s (1330 heal)
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=0m55s (1960 heal crit)
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=2m50s (2014 heal crit)
https://www.youtube.com/watch?v=VbYnyfaL7J8&t=4m35s (2041 heal crit)

Here are 5 videos just now of a paladin (no healing light) on anathema (sensure) using 22 healing boots.

Sensure heals (22 healing)
https://www.youtube.com/watch?v=VhJIMWq77lo 
https://www.youtube.com/watch?v=zrT3lqnskuE (2115 crit)
https://www.youtube.com/watch?v=umm0JfDrXDc
https://www.youtube.com/watch?v=aK4iLqLu47c (1423 normal heal and 2107 crit heal)
https://www.youtube.com/watch?v=-julPN3E07Q (his talents)
https://www.youtube.com/watch?v=nThD8ZVEFhQ 

22 healing gave a 1423 heal and 2115, 2017 heal crit

Another Anathema paladin 
https://youtu.be/AriaDSeguXc 
Happygoat paladins rank 8 holy light with 23 healing as retail jamaz in video = 
(with 3/3 healing light =12% extra)
1505 
1599 
1558 
This paladin Happygoat I just recorded on anathema with no gear but only +23 healing and he was healing as much. The paladin on anathema is holy and has the talent that gives him 12% more heals. Just to prove that anathema paladin was using rank 8 heals from the start, i told him to use rank 9 and it healed for 1851
The paladin on retail in the other video has no 12% (0/3 healing light from holy talents) 

yet work it out.
Jamaz (retail paladin) with 3/3 healing light 
1401 x 0.12 = 168 + 1401 = 1569 rank 8 heals

This means Jamaz had 40 healing maximum since he isn't higher on most heals than the anathema paladin. He did NOT have helm/pants enchants from zg because his healing is proven to be less.

Jamaz most likely has no more than 40 healing. This needs to be fixed to be 23% scaling
If he was more than 40 healing he would of outhealed Happygoat.
https://youtu.be/AriaDSeguXc

Jamaz has 40 healing and therefore a 23% scaling should be placed on crystal restore. Fix please

**Comment by GuybrushGit** [comment]
What you're asking is for is a 200% coefficient. That is just plain wrong.
He most likely has more than 22 healing.

**Comment by Mostprovidedlinks** [comment]
Feel free to prove what extra healing/spell damage gear he has

**Comment by Mostprovidedlinks** [comment]
You mean a 40.909% coefficient.

**Comment by GuybrushGit** [comment]
Every single item and spell in the game is hard capped at 100%, nothing can have over 100%. 
You're asking for something to do 40% * 5 ticks = 200% coeff. 
He had to have over 22 healing.

**Comment by Mostprovidedlinks** [comment]
The ticks aren't 200% coefficient. They are 41%

**Comment by GuybrushGit** [comment]
The person you're quoting on the Hakkari Manslayer doesnt understand how coefficients work, says 200% and then describes getting 100%. Do you really think we should change anything based on comments of people who can't even do math?

**Comment by thepparker** [comment]
Dealing 100% of your spell power as damage and then getting that same amount of life back does not equal a 200% coefficient, which is what the comments for the manslayer describe.

Jamalz has more than 20 spellpower, which is clearly demonstrated at https://youtu.be/kr_GlmzQ_M4?t=582 where his holy light (assuming rank 8, which is a safe assumption since it's the only rank that can heal for that much) heals for 1429. The base top-end healing for holy light is 1389, which means his heal dealt 34 extra healing. At a coefficient of 0.71 (2.5/3.5), this means he has at least 47 +healing.

To achieve ticks of 143 with a crystal spire (with 100% coefficient), he needs to have at least 45 +healing, which I just demonstrated he clearly has. Therefore, this report is invalid.

**Comment by Mostprovidedlinks** [comment]
Definitely incorrect. Happygoat without any spell damage or healing gear is healing more than the rank 8 holy light range. How do you explain that?

**Comment by thepparker** [comment]
I already proved you wrong. You already mentioned Happygoat has the holy talents. As I said, 3 heals is not enough to gauge the range on a spell.

**Comment by Mostprovidedlinks** [comment]
I have a video with 100 spells. Let see

**Comment by thepparker** [comment]
Ok, sure, I concede that I didn't include the level scaling in my first post. At level 60 a Holy Light rank 8 will heal for a base of 1272-1415. Using the healing in my previous example as a top-end would put him at around 20 +healing, so it is apparently not a good example.

Let's look at https://youtu.be/kr_GlmzQ_M4?t=1076 instead. His holy light critically heals for 2164. We can calculate the non-crit heal to be 1442.67 (2164/1.5 since paladins have no crit scaling). This means he has 1442.67 - 1415 = 27.67 extra healing on this spell. Again, at a coefficient of 0.71, this means he has at least 39 bonus healing from gear.

Testing locally, if I only equip Lawbringer Chestguard (with a +healing of 22) and have no talents assigned, my maximum heal is 1430 (1415 + 0.71 * 22).

**Comment by Mostprovidedlinks** [comment]
I have 12 videos, in the first one I got him to heal without gear. Then in every video when he is healing, the entire time you see him healing,. i told him to equip 26 spell healing and then 22 spell healing. 
in the combat list with 26 healing (accidentally wrote 27 in video) 26 spell healing is giving 1430 and 1427 heals

**Comment by Mostprovidedlinks** [comment]
the coefficient could be 39-41% idk but here I have 12 videos ill post

**Comment by QAkvastskaft** [comment]
The paladin in the video is wearing both Lawbringer belt and Lawbringer chest. He therefore has more than +22 healing
Proof: http://i.imgur.com/iMideJi.png
Pictures taken from https://youtu.be/VbYnyfaL7J8?t=25
and from http://db.vanillagaming.org/?item=16858

Chest provides +22 healing and belt provide +18 healing both have updated stats since the skin is updated

Summary:
Crystal restore should scale with spell power/healing power. -> confirmed
The scaling is not proved to be above 100% and should therefore, until conclusive evidence is found, be made to follow the common spell coefficient rules. i.e 100% (20% per tick for dots if I'm not mistaken)

**Comment by Mostprovidedlinks** [comment]
Very good find QAkvastskaft  

This means its 40 x 0.23 = 9 healing

Therefore it should scale at 23%

**Comment by ImperfectCell** [comment]
Yeah works out to 23% if he had a 9 increase. I for one agree to this.

**Comment by thepparker** [comment]
Just to put the pin in this, the crystal restore should be and is currently 100%. The ticks of 143 you see are a chance rounding, hence the single tick of 142 we see. 40 spell power at 100% co-efficient -> 714 total healing, or 142.8 per tick. 

See #716 for more information

**Comment by ImperfectCell** [comment]
40 spell healing is giving a 9 heal increase.

**Comment by thepparker** [comment]
Just give it up man. https://youtu.be/VbYnyfaL7J8?t=359 it ticks for 142 after ticking for 143
