### ISSUE TITLE
Ignite damage too high

### ISSUE THREAD

**Issue by quasexort** [elysium-project/server#618]
The way it should work is suppose you have 5 Fireball crits that generate the ignite, then every 2 seconds you get a 20% tick from those 5 fireball crits so essentially you get a Fireball's crit worth of damage every  two seconds (5 * 20% = 1).  However, it will be slightly higher if the boss has curse of elements / fire vulnerability / nightfall.  With all these debuffs the ignite will be roughly 45% (1.1 * 1.15 * 1.15 ~= 1.45475) higher than a fireball crit, but what we are seeing are much higher ignite ticks.  My highest fireball crit currently has been like 3.7k, but let's assume someone could somehow crit for 5k, then the max ignite they could ever see would be 7,273 damage.  Right now it isn't uncommon to see people having ignites well into the 10k+ range which shouldn't even be possible.

**Comment by thepparker** [comment]
Ignites "roll" with each critical hit by a fire spell from a mage with ignite talents. This means that every time a crit occurs, the previous application's REMAINING damage (i.e. hasn't expired) is added to the new application. Technically, with enough mages consistently landing critical hits, your ignite damage can be infinite.

So let's say mage A crits for 3k, he applies an ignite for 0.4x3000 = 1200, which is 600 per tick.
2 seconds goes past, 1 tick of ignite applies. There is now 1 tick remaining for 600 damage.

Mage B crits for 2k, our first ignite has not expired yet so now we apply another stack to the ignite and "roll" the previous ignite's damage over onto the new ignite as well. The ignite damage is now 600 + 0.4x2000 = 1400, 700 damage per tick.

Mage A crits again for 3k  before the first tick of mage B's ignite occurs. Now we roll over the previous ignite and add more to it again! 0.4x3000 + 1400 = 2600, 1300 per tick.
2 seconds pass, 1 tick is applied. 1 tick remaining for 1300 damage.

Mage B crits again for 2k, and we roll over the remaining tick. 0.4x2000 + 1300 = 2100, 1050 damage per tick.
... etc.

There is no cap on the damage, and so you can quickly see how ignites can become rather large with enough mages landing enough crits. The number of stacks further multiplies the amount of damage being dealt.

**Comment by quasexort** [comment]
I didn't play mage in vanilla but my impression when talking to other mages and watching videos of fire mages raiding from 2006 is that once the ignite reaches 5 stacks any additional crits simply reset the ignite timer and DOES NOT add more damage to the ignite. The reason this matters is that currently if we have this unlimited stacking ignite then Cthun can be killed really fast during a phase 2 vul if you just bring like 10 mages to the raid and have them all pop CDs.  I don't think I've ever seen something like this in retail vanilla since I believe the ignite was always capped at the first 5 crits.

Curse video of Loatheb from mage POV with combat log:
https://www.youtube.com/watch?v=bMWKNeIISmo

Notice the ignite damage is not increasing after reaching 5 stacks.

**Comment by Slicy** [comment]
The fact you are able to keep on stacking it before the remaining damage occurs is a blizzlike bug players are capable of performing easily intentionally or not nowadays. It was only fixed once the entire Ignite mechanic was overhauled in TBC giving each mage his own ignite.

Ignite damage is supposed to cap upon reaching the 5 stacks as said above. You aren't meant to keep on infinitely ramping up the damage before a remaining damage tick. Doing so is just exploiting a flaw in the ignite mechanic during vanilla.

Here is a reference about it : 
_"Sometimes a single tick of Ignite will do its damage and then also be added to a second Ignite if it lands just before the tick. This means that one or both ticks of Ignite can do twice the expected damage. This is often mistaken to mean the old "rolling" ignite system from pre-2.0 (see past changes) is still present. The condition for this bug seems to be precise timing, making it difficult to exploit to any advantage"_

**Comment by thepparker** [comment]
To reach 200k ignites you have to be extremely lucky or exploiting other (likely unintended on this server) mechanics in conjunction with ignite. Even on Loatheb they have ignite falling off before it becomes too extreme. I do agree though that it appears to cap at 3.9k in that video since subsequent crits do not increase the tick damage. The only increase is at around 1:40 where CoE is finally applied.

**Comment by killerduki** [comment]
https://www.youtube.com/watch?v=MV_hX25_8m0
**Uploaded on Oct 30, 2006**

The new "crit" was not added, new crit did not overwrite lower crits , it was just the first 5 Crits.

The 5th Crit this guy did was at 00:43 while at 00:46 Ignite started to tick 3050 , the same damage was never overwritten or changed by the new crits until the very end.

00:47 you see the person did new Crit but the number of Ignite did not change and it remained 3050 like it is until the end.

**Comment by quasexort** [comment]
I think there's enough proof to show that ignites should not be doing this much damage.
http://realmplayers.com/RaidStats/FightOverview.aspx?Raid=71483&Fight=9

**Comment by StadenElysium** [comment]
Superseded by https://github.com/elysium-project/server/issues/748.
