### ISSUE TITLE
NPCs incorrectly considered civilian: CONFIRMED 

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/server#655]
The following NPCs are incorrectly considered civilian without being marked as such.
Nag'zehn id: 4545
Bor'zehn id: 4546
Heralath Fallowbrook id: 4510 
Lomac Gearstrip id: 4081

They should get their hidden civilian tag shown (edited)

Original posts on bug tracker here:
https://elysium-project.org/bugtracker/issue/4415
https://elysium-project.org/bugtracker/issue/2063
https://elysium-project.org/bugtracker/issue/3606

**Comment by thepparker** [comment]
Is the issue that the tag should be removed, or that it should actually be properly sent to the client? There are a number of NPCs marked as civilian which do not show as civilian in their tooltips. Guard Parker (Redridge) springs to mind since I have received a DK from him previously. I think it is the latter.

**Comment by QAkvastskaft** [comment]
I think properly sent to the client is the way to go
