### ISSUE TITLE
Won item does not transfer

### ISSUE THREAD

**Issue by chidyco** [elysium-project/server#698]
I was finishing a Cath run, which my group and I had started before the server crash (that happened at around 5:30 AM server time on 5/13/2017). We finished, Hand of Righteousness dropped. I won the roll, but the item didn't transfer to my bags. My bags were not full. I checked the female mob as well, but it was not on her, didn't have the option to loot. The mage who randomly won the shield also said the shield wasn't in his bags either.

I would appreciate it if this item could be restored to me!

Thanks,

Elysium PvP
Proteindrink (Fem Dwarf Pally 41)

![wowscrnshot_051217_220325](https://cloud.githubusercontent.com/assets/28666413/26022366/40ce0a56-3761-11e7-86ff-f367842228c3.jpg)

**Comment by Phoosy** [comment]
Github is not a place for item restorations - this kind of issue goes into an in-game ticket. However, seeing as how you lost the item to what appears to be the minor rollback from the server crash or some sort of fault of the server, we cannot restore the item - we don't restore items lost due to this unless they meet the requirements set out in the Terms of Use, linked here: https://forum.elysium-project.org/topic/21966-terms-of-use-rules-regulations/

Recommending this be closed.

**Comment by brotalnia** [comment]
That hammer with the same icon as divine shield in the Runecloth Bag at the top looks like your Hand of Righteousness to me.

**Comment by chidyco** [comment]
Bro, I saw it this morning in that bag... I must have been too tired, I don't know.

**Comment by chidyco** [comment]
Phoosy, I couldn't submit an 'item' ticket, it kept referring me to the bugtracker.
