### ISSUE TITLE
Sulfuras, Hand of Ragnaros - should not stack with spell damage, incorect DoT mechanic

### ISSUE THREAD

**Issue by fidbugs** [elysium-project/server#737]
Curently Sulfuras's both procs, fireball and DoT are scaling with bonus spell damage and DoT component(75 damage over 10 seconds) has wrong scripting.

Few videos of paladins and shamans using Sulfuras prove this claim.

Paladin, 83 spell damage on gear - https://www.youtube.com/watch?v=AbamezcjYvk
(2:47, 4:01, 4:12, 7:05, 10:35)

Shaman, at least 83 spell damage in Warlord set - https://www.youtube.com/watch?v=ja1j7xWpB3w
(2:00, 2:31, 3:16)

Shaman, 53 spell damage on gear - https://www.youtube.com/watch?v=J-qxZAx1bjQ
(3:32, 9:56, 14:09)

_Regarding not scaling_ - in each video Fireball occurrences are listed below each video, which makes it visible that there is no scaling. 

_Regarding the DoT mechanic:_

_"WoW 60 - Shaman with Sulfuras"_ on14:09 and onward shows no scaling of DoT mechanic and that it should be triggered 5 times for 15 damage every 2 seconds thru 10 seconds(on 2nd 4th 6th 8th and 10th second).

Also same video shows that DoT component remains even if Fireball has been resisted. You can see that on 3:32 when Fireball gets resisted, but target is still affected by DoT.

**To fix:**
a. remove spell scaling from item proc 
b. apropriate DoT mechanic(5x 15 damage every two seconds)
c. even if Fireball gets resisted, DoT remains/affects target

**Comment by killerduki** [comment]
Perhaps you should stop giving Links who date from 2010 and 2013 with unreliable information.

Here is evidence that this report should be invalid : 

https://www.youtube.com/watch?v=ovhRqAxnXqg

**Uploaded on Nov 19, 2006**

1:36 = Boule de feu (translation is fireball)  271(78 resist) = **349** without any critical strike.
3:26 = Boule de feu (translation is fireball)  94(234 resist) = 328 without any critical strike.

1- If Sulfuras Fireball did not scale = the damage would never been higher than 333 or at least some of the procs would have gone down to 273, which in the video from 2006 we have evidence that 1 of the fireballs was higher than 333. 

2- How did you figure out that the Paladin have "83" spell Damage or the Shamans?
The Patch on the Videos you try to show is probably from early days where Spell Damage was almost non existent . 

3- On your 1st Video , if "83" spell damage (according to your logic) should not increase the damage of the Fireball , then how come at 4:01 he did 340 damage ? https://cdn.discordapp.com/attachments/230437139463012353/313867160403574785/unknown.png
(Sulfuron Hammer maximum damage is 333, which mean according to you it shouldn't hit 340 at any cost). 

4- On your 2nd Video if "83" spell damage Shaman (according to your logic) should not increase the damage of the Fireball , then how come at 2:31 he did 483 critical (if you go according to logic for 50% in regards to spells crit) then the original damage would been 362 (which is 32 damage higher than the "maximum damage")

5- Your 3rd Video description doesn't even say if it is Retail or not , neither any explanation on the description , the Fireballs (assuming) could have done also the "minimum damage" since Sulfuron hammer does have Minimum and Maximum damage in which on previous Videos we all seen it goes beyond "Maximum" damage or we can say it could have been coincidence that in this Video probably it did the "Minimum" damage.

Please next time give evidence from 2006 with proper information , this report is Invalid , but up to QA .

**Comment by fidbugs** [comment]
In the video you have linked Gollemag is affected by Improved Scorch which increases fire damage taken by 10%, thus the 349 hit. Still 328 hit is below 334. Not to mention that no gear is shown in the video so we have no idea what does he wear to even consider spell scaling.

1. - There are few ways in which damage done by spells can be increased other than bonus spell damage, for instance the mentioned Improved Scorch(we will see one more down the line). every time that it is higher than 334 it is affected by one such effect.

2. - By looking at the videos actually. If you did the same you would see that gear is shown, they have sufficient amount of spell damage on it so we can judge if it scaled or not. And not its not early, its post 1.10, we have librams, latest paladin T2 and latest PvP gear.

3. - At 4:01 in first video, target is affected by Berserking buff, it increases all damage received by 10% - thus higher than average hit.

4. - You are bad at math, 483/1.5=322, that is under the maximum of 334.

5. - Video is obviously vanilla material, if you cant see that from the actual video material presented, here is something to look at. http://www.warcraftmovies.com/movieview.php?id=14838
