### ISSUE TITLE
mmap Map System crashing server on startup

### ISSUE THREAD

**Issue by fatalmatt** [elysium-project/server#75]
I've used the extractors correctly and the mmap files that they output keep giving the same error and crashing the server upon start up @ "Starting Map System". Almost makes me think that there is something wrong with the extractor source code... Has anyone else had the same problem..?

Error:
`src\game\Maps\MoveMap.cpp:173: Error: Assertion in MMAP::MMapManager::loadMap failed: data`

**Comment by DonkeyKongRacer** [comment]
This is not an issue with the source. You have to compile the core in 64 bits. The issue you're getting is because you're running the core as a 32 bit application on windows, so it's limited to 2 Gb of ram, and since loading MMaps is a very heavy process in terms of memory, it crashes.
Make sure you recompile ACE in 64 bits so you can compile the core in 64 bits.

**Comment by Locario** [comment]
same problem in Linux, can anyone describe simply how to compile core in Linux 64 bits?

with mmaps from mangos core dont crash

**Comment by russkiemafia** [comment]
It simply says that your mmaps are not compatible with this core. You should disable them via configuration.

**Comment by Locario** [comment]
i have lot of errors starting mangosd. the two files i search from that list simply dont exist, also mmaps_disable option in conf file dont help, seems displaying mmaps errors before crash

**Comment by fatalmatt** [comment]
@DonkeyKongRacer I have compiled it in 64 bits since the start.. The mmap causing the issue seems to be Kalimdor "Map ID: 1".
