### ISSUE TITLE
Children's Week Quests

### ISSUE THREAD

**Issue by darkwerk13** [elysium-project/server#789]
I can only get two of the quests for Children's Week. The one for the ice cream and the one for the  autograph.

I'm above level 10.

https://web.archive.org/web/20070508230637/http://www.wowwiki.com:80/Quest:Spooky_Lighthouse

https://web.archive.org/web/20070526084217/http://www.wowwiki.com:80/Quest:The_Stonewrought_Dam

https://web.archive.org/web/20070529232504/http://www.wowwiki.com:80/Quest:A_Warden_of_the_Alliance

**Comment by brotalnia** [comment]
Indeed. The problem is "The Bough of the Eternals" requires level 60, and the "The Stonewrought Dam" has that one as a requirement. Not sure if it is supposed to require 60.

A Warden of the Alliance is started from a guy in Duskwood, instead of the orphan. I think that's wrong, since the quest text is from the perspective of the orphan.

**Comment by darkwerk13** [comment]
Thanks for the update. That makes sense. I will talk to that guy in Duskwood as well. Currently I'm in my 40s. Characters in their 20s can't even get the autograph quest.
