### ISSUE TITLE
Item sold

### ISSUE THREAD

**Issue by Gardzjin** [elysium-project/server#793]
Item *Skull of impending doom* accindentally sold to a vendor and was not able to repurchase
Name Goraj

**Comment by Phoosy** [comment]
This is an issue for our in-game ticket system. Use the Stuck prompts to enter your ticket using the ? help icon.

**Comment by Gardzjin** [comment]
in-game ticket system dont work

**Comment by Sabre142** [comment]
File the ticket under Character Stuck

**Comment by Gardzjin** [comment]
And what i must do?

**Comment by QAkvastskaft** [comment]
Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Then use the info in the following link to write the message: https://forum.elysium-project.org/topic/47134-quest-item-restoration/

Thank you
