### ISSUE TITLE
Devilsaurs resist spells too often

### ISSUE THREAD

**Issue by Brodda** [elysium-project/server#845]
When fighting a devilsaur on my mage like 50% of my spells are being resisted. Heres a video from 2006 that shows a mage kiting a devilsaur and almost zero resists.

http://www.warcraftmovies.com/movieview.php?id=17766

I'm unable to record a video of me shooting frostbolts at the devilsaurs because they are being camped 24/7 by opposite faction so a dev should test it on a test realm.

**Comment by Brodda** [comment]
Here is a video from Elysium. You can see how many resists I get which doesn't happen in that 2006 video. Clearly Devilsaurs needs to be adjusted on Elysium so that mages can also kill them.

**Comment by kampeador** [comment]
All devilsaurs currently have 200 to each resists(except holy), while King Mosh has 0. I have a very old mangos source with SDB from 20 december 2006 with the same issue.
The problem is, that each devilsaur type is unique.
1. White Devilsaur had a magic resistance(hard for casters)
http://db.vanillagaming.org/?npc=6498
2. Ironhide Devilsaur had alot of armor(hard for melees/hunters)
http://db.vanillagaming.org/?npc=6499
3. Tyrant Devilsaur had AOE fear.
4. King Mosh had taken all their stats and abilities togather. A very old database for ascent based emulator mentiones that his magic resistances were 270.
SDB devs probably adjusted all of them according to White Devilsaurs and King Mosh left with 0.
Video prooves that pt 2 and 3 are probably correct. It would be nice to find more sources regarding pt. 1 and 4.

**Comment by GuybrushGit** [comment]
Found no evidence of the high magic resistance. I even found a comment of a 55 frost mage who easily took down a white devilsaur: http://web.archive.org/web/20070531100800/http://www.thottbot.com:80/c6498

Bestiary only has 53 fire resist on the white devilsar, nothing on King Mosh.
Theres a couple of other things missing tho. Their damage is too low compared to the comments and bestiary and King Mosh should be immune to most mechanics: 
http://web.archive.org/web/20070531110339/http://www.thottbot.com:80/c6584
http://web.archive.org/web/20080621103053/http://wow.allakhazam.com:80/db/mob.html?wmob=6584

**Comment by kampeador** [comment]
There are some videos available:
White Devilsaur:
https://www.youtube.com/watch?v=sqotU1FcbAU
King Mosh:
https://www.youtube.com/watch?v=sqotU1FcbAU

**Comment by QAkvastskaft** [comment]
Fixed here: https://forum.elysium-project.org/topic/53089-development-update-30082017/
