### ISSUE TITLE
<Master of Elements>[3/3] (fire Mage) is broken

### ISSUE THREAD

**Issue by Myxtap** [elysium-project/server#853]
**Master of Elements** stopped working after yesterdays disconect: now this talent doesn't refund any mana.

![1](https://cloud.githubusercontent.com/assets/28946586/26443027/78fc25c4-413f-11e7-9601-0978193cad87.jpg)

**Comment by thepparker** [comment]
It still works, it just doesn't proc a bunch of times on AoE abilities. Nor will it proc for crits on secondary targets. In the current implementation you have exactly your crit chance to proc MoE rather than an ever increasing chance proportional to the number of mobs you are hitting.

It is debatable whether it should be allowed to proc on any of the mobs hit if it's a crit, but limited to proccing only once.

**Comment by eron-elysium** [comment]
This issue should have have been closed.   There is no such thing as a primary or secondary target when you cast an AOE spell.  If any of the targets are crit, MOE should proc.  This is well documented proper behavior for retail vanilla.

**Comment by aesdotjs** [comment]
This ticket shouldn't have been closed... In the current state its broken and doesn't reflect vanilla and more than that its unreliable the way it is.. Ex: if you nova flame strike as an elemental mage you can have 5 crits but no crit on your main target you won't get any mana. Fix please.
