### ISSUE TITLE
Darrowshire- The quest Ledger from Tanaris can't be completed

### ISSUE THREAD

**Issue by Ripper007** [elysium-project/server#901]
The quest Ledger from Tanaris ( id 4450) can't be completed. I have all the items required for completion:
Goodsteel Ledger (id11727), Solid Crystal Leg Shaft x20 (id 11725), Overdue Package (id 11724) and Goodsteel's Balanced Flameberge (id 11723). I tried almost all the usual workarounds( only abandoning quest left) but from what i checked on issues, that problem should be solved already, there was a fix for that (#110->#231).

**Comment by TNadal** [comment]
abandon and re-accept is still required sometimes and should let you turn it in.

**Comment by Kolmarwow** [comment]
as the guy above me said, abandoning and re-accepting the quest will fix it. i've noticed that this bug only happens when you get over the required amount of items needed for the quest. 

so in this case for example, you need 20x Solid Crystal Leg Shafts, and each spider has a chance of dropping like 0-3 legs if i remember right. so if you end up getting 21x legs, the quest will glitch out and won't let you turn it in. the only way to fix it is by abandoning and re-accepting.

**Comment by thepparker** [comment]
Put one of the items in the bank at Gadgetzan and take it out again, you will then be able to turn it in. Abandoning this quest is obviously not ideal since you have to pick it up in Searing Gorge...

**Comment by Ripper007** [comment]
Sorry but you (all) are missing the point and as i said, I already tried all the options ( except the abandoning the quest). The fix in #231 should've taken care of the issue but for this quest it didn't. Maybe is what Kolmarwow pointed out and that should help isolate and fix this and/or other quests that might be affected.

**Comment by GuybrushGit** [comment]
#231 fixes a diferent issue. I tested going over the required item count and it does not reproduce the issue.

**Comment by robmonte** [comment]
Still can't get the ledger to spawn for me either on Darrowshire.
