### ISSUE TITLE
Battle shout rank 5 + Fury talents...

### ISSUE THREAD

**Issue by Sabinonelysium** [elysium-project/server#907]
According to the tooltip (buff near minimap) Rank 5 battle shout is giving me 140 attack power. This is wrong, I took off the buff and did the math while looking at my stats in the character menu and it does give me 166 AP. The rank 5 is supposed to give 156 AP. I have 4/5 imp battle shout giving me 20% more bonus on Battle Shout's AP buff. 0.2 X 156 = 31.2. 156 + 31.2 = 187AP where I'm getting 166AP. Not only is the buff wrong on the top lying about my actual AP given, the actual AP given is wrong given my talents.

**Comment by QAkvastskaft** [comment]
Rank 5 battle shout gives 130 attack power without accounting for talent. http://db.vanillagaming.org/?spell=11550
You are supposed to get 130*1.2=156 attack power.

The bug seems to be that when having only 4/5 of the talent you still get the full bonus of 5/5
Having 4/5 talent gives 231 attack power from rank 6 when you are supposed to get 222
185*1.2=222 and 185*1,25=231

**Comment by GuybrushGit** [comment]
This isnt bugged, battle shout scales with level. At level 60 you're supposed to get 193 from r6. 
With 4/5 talent, 193\*1.20 = 231
